.section .late_rodata
dlabel D_i6_801A7ED0
/* EBFB80 801A7ED0 3C8EFA35 */ .float 0.01745329238


.section .text
/* Generated by spimdisasm 1.19.1.dev0 */

glabel func_i6_801A5560
/* EBD210 801A5560 27BDFFA8 */  addiu       $sp, $sp, -0x58
/* EBD214 801A5564 AFB10024 */  sw          $s1, 0x24($sp)
/* EBD218 801A5568 AFB00020 */  sw          $s0, 0x20($sp)
/* EBD21C 801A556C 00A08025 */  or          $s0, $a1, $zero
/* EBD220 801A5570 00808825 */  or          $s1, $a0, $zero
/* EBD224 801A5574 AFBF002C */  sw          $ra, 0x2C($sp)
/* EBD228 801A5578 AFB20028 */  sw          $s2, 0x28($sp)
/* EBD22C 801A557C F7B40018 */  sdc1        $fs0, 0x18($sp)
/* EBD230 801A5580 AFA60060 */  sw          $a2, 0x60($sp)
/* EBD234 801A5584 AFA70064 */  sw          $a3, 0x64($sp)
/* EBD238 801A5588 0C00D792 */  jal         PlayerShot_Initialize
/* EBD23C 801A558C 02002025 */   or         $a0, $s0, $zero
/* EBD240 801A5590 3C01801A */  lui         $at, %hi(D_i6_801A7ED0)
/* EBD244 801A5594 C4347ED0 */  lwc1        $fs0, %lo(D_i6_801A7ED0)($at)
/* EBD248 801A5598 C6240000 */  lwc1        $ft0, 0x0($s1)
/* EBD24C 801A559C 3C128014 */  lui         $s2, %hi(gCalcMatrix)
/* EBD250 801A55A0 2652BBC8 */  addiu       $s2, $s2, %lo(gCalcMatrix)
/* EBD254 801A55A4 46142182 */  mul.s       $ft1, $ft0, $fs0
/* EBD258 801A55A8 8E440000 */  lw          $a0, 0x0($s2)
/* EBD25C 801A55AC 00003025 */  or          $a2, $zero, $zero
/* EBD260 801A55B0 44053000 */  mfc1        $a1, $ft1
/* EBD264 801A55B4 0C0017A4 */  jal         Matrix_RotateY
/* EBD268 801A55B8 00000000 */   nop
/* EBD26C 801A55BC C6280004 */  lwc1        $ft2, 0x4($s1)
/* EBD270 801A55C0 8E440000 */  lw          $a0, 0x0($s2)
/* EBD274 801A55C4 24060001 */  addiu       $a2, $zero, 0x1
/* EBD278 801A55C8 46144282 */  mul.s       $ft3, $ft2, $fs0
/* EBD27C 801A55CC 44055000 */  mfc1        $a1, $ft3
/* EBD280 801A55D0 0C001751 */  jal         Matrix_RotateX
/* EBD284 801A55D4 00000000 */   nop
/* EBD288 801A55D8 C63000EC */  lwc1        $ft4, 0xEC($s1)
/* EBD28C 801A55DC 8E440000 */  lw          $a0, 0x0($s2)
/* EBD290 801A55E0 24060001 */  addiu       $a2, $zero, 0x1
/* EBD294 801A55E4 46148482 */  mul.s       $ft5, $ft4, $fs0
/* EBD298 801A55E8 44059000 */  mfc1        $a1, $ft5
/* EBD29C 801A55EC 0C0017F8 */  jal         Matrix_RotateZ
/* EBD2A0 801A55F0 00000000 */   nop
/* EBD2A4 801A55F4 C6240180 */  lwc1        $ft0, 0x180($s1)
/* EBD2A8 801A55F8 8E440000 */  lw          $a0, 0x0($s2)
/* EBD2AC 801A55FC 24060001 */  addiu       $a2, $zero, 0x1
/* EBD2B0 801A5600 46142182 */  mul.s       $ft1, $ft0, $fs0
/* EBD2B4 801A5604 44053000 */  mfc1        $a1, $ft1
/* EBD2B8 801A5608 0C0017A4 */  jal         Matrix_RotateY
/* EBD2BC 801A560C 00000000 */   nop
/* EBD2C0 801A5610 C628017C */  lwc1        $ft2, 0x17C($s1)
/* EBD2C4 801A5614 8E440000 */  lw          $a0, 0x0($s2)
/* EBD2C8 801A5618 24060001 */  addiu       $a2, $zero, 0x1
/* EBD2CC 801A561C 46144282 */  mul.s       $ft3, $ft2, $fs0
/* EBD2D0 801A5620 44055000 */  mfc1        $a1, $ft3
/* EBD2D4 801A5624 0C001751 */  jal         Matrix_RotateX
/* EBD2D8 801A5628 00000000 */   nop
/* EBD2DC 801A562C C7B00060 */  lwc1        $ft4, 0x60($sp)
/* EBD2E0 801A5630 C7B20064 */  lwc1        $ft5, 0x64($sp)
/* EBD2E4 801A5634 C7A40068 */  lwc1        $ft0, 0x68($sp)
/* EBD2E8 801A5638 8E440000 */  lw          $a0, 0x0($s2)
/* EBD2EC 801A563C 27A5004C */  addiu       $a1, $sp, 0x4C
/* EBD2F0 801A5640 27A60034 */  addiu       $a2, $sp, 0x34
/* EBD2F4 801A5644 E7B0004C */  swc1        $ft4, 0x4C($sp)
/* EBD2F8 801A5648 E7B20050 */  swc1        $ft5, 0x50($sp)
/* EBD2FC 801A564C 0C001A5C */  jal         Matrix_MultVec3f
/* EBD300 801A5650 E7A40054 */   swc1       $ft0, 0x54($sp)
/* EBD304 801A5654 C6260000 */  lwc1        $ft1, 0x0($s1)
/* EBD308 801A5658 8E440000 */  lw          $a0, 0x0($s2)
/* EBD30C 801A565C 00003025 */  or          $a2, $zero, $zero
/* EBD310 801A5660 46143202 */  mul.s       $ft2, $ft1, $fs0
/* EBD314 801A5664 44054000 */  mfc1        $a1, $ft2
/* EBD318 801A5668 0C0017A4 */  jal         Matrix_RotateY
/* EBD31C 801A566C 00000000 */   nop
/* EBD320 801A5670 C62A0004 */  lwc1        $ft3, 0x4($s1)
/* EBD324 801A5674 8E440000 */  lw          $a0, 0x0($s2)
/* EBD328 801A5678 24060001 */  addiu       $a2, $zero, 0x1
/* EBD32C 801A567C 46145402 */  mul.s       $ft4, $ft3, $fs0
/* EBD330 801A5680 44058000 */  mfc1        $a1, $ft4
/* EBD334 801A5684 0C001751 */  jal         Matrix_RotateX
/* EBD338 801A5688 00000000 */   nop
/* EBD33C 801A568C C63200EC */  lwc1        $ft5, 0xEC($s1)
/* EBD340 801A5690 8E440000 */  lw          $a0, 0x0($s2)
/* EBD344 801A5694 24060001 */  addiu       $a2, $zero, 0x1
/* EBD348 801A5698 46149102 */  mul.s       $ft0, $ft5, $fs0
/* EBD34C 801A569C 44052000 */  mfc1        $a1, $ft0
/* EBD350 801A56A0 0C0017F8 */  jal         Matrix_RotateZ
/* EBD354 801A56A4 00000000 */   nop
/* EBD358 801A56A8 C6260180 */  lwc1        $ft1, 0x180($s1)
/* EBD35C 801A56AC 8E440000 */  lw          $a0, 0x0($s2)
/* EBD360 801A56B0 24060001 */  addiu       $a2, $zero, 0x1
/* EBD364 801A56B4 46143202 */  mul.s       $ft2, $ft1, $fs0
/* EBD368 801A56B8 44054000 */  mfc1        $a1, $ft2
/* EBD36C 801A56BC 0C0017A4 */  jal         Matrix_RotateY
/* EBD370 801A56C0 00000000 */   nop
/* EBD374 801A56C4 C62A017C */  lwc1        $ft3, 0x17C($s1)
/* EBD378 801A56C8 8E440000 */  lw          $a0, 0x0($s2)
/* EBD37C 801A56CC 24060001 */  addiu       $a2, $zero, 0x1
/* EBD380 801A56D0 46145402 */  mul.s       $ft4, $ft3, $fs0
/* EBD384 801A56D4 44058000 */  mfc1        $a1, $ft4
/* EBD388 801A56D8 0C001751 */  jal         Matrix_RotateX
/* EBD38C 801A56DC 00000000 */   nop
/* EBD390 801A56E0 C63200E8 */  lwc1        $ft5, 0xE8($s1)
/* EBD394 801A56E4 8E440000 */  lw          $a0, 0x0($s2)
/* EBD398 801A56E8 24060001 */  addiu       $a2, $zero, 0x1
/* EBD39C 801A56EC 46149102 */  mul.s       $ft0, $ft5, $fs0
/* EBD3A0 801A56F0 44052000 */  mfc1        $a1, $ft0
/* EBD3A4 801A56F4 0C0017A4 */  jal         Matrix_RotateY
/* EBD3A8 801A56F8 00000000 */   nop
/* EBD3AC 801A56FC C62600E4 */  lwc1        $ft1, 0xE4($s1)
/* EBD3B0 801A5700 8E440000 */  lw          $a0, 0x0($s2)
/* EBD3B4 801A5704 24060001 */  addiu       $a2, $zero, 0x1
/* EBD3B8 801A5708 46143202 */  mul.s       $ft2, $ft1, $fs0
/* EBD3BC 801A570C 44054000 */  mfc1        $a1, $ft2
/* EBD3C0 801A5710 0C001751 */  jal         Matrix_RotateX
/* EBD3C4 801A5714 00000000 */   nop
/* EBD3C8 801A5718 44800000 */  mtc1        $zero, $fv0
/* EBD3CC 801A571C C7AA0070 */  lwc1        $ft3, 0x70($sp)
/* EBD3D0 801A5720 8E440000 */  lw          $a0, 0x0($s2)
/* EBD3D4 801A5724 27A5004C */  addiu       $a1, $sp, 0x4C
/* EBD3D8 801A5728 27A60040 */  addiu       $a2, $sp, 0x40
/* EBD3DC 801A572C E7A00050 */  swc1        $fv0, 0x50($sp)
/* EBD3E0 801A5730 E7A0004C */  swc1        $fv0, 0x4C($sp)
/* EBD3E4 801A5734 0C001A5C */  jal         Matrix_MultVec3f
/* EBD3E8 801A5738 E7AA0054 */   swc1       $ft3, 0x54($sp)
/* EBD3EC 801A573C 8E440000 */  lw          $a0, 0x0($s2)
/* EBD3F0 801A5740 0C001AAE */  jal         Matrix_GetYRPAngles
/* EBD3F4 801A5744 27A5004C */   addiu      $a1, $sp, 0x4C
/* EBD3F8 801A5748 240E0001 */  addiu       $t6, $zero, 0x1
/* EBD3FC 801A574C A20E0000 */  sb          $t6, 0x0($s0)
/* EBD400 801A5750 C7B00040 */  lwc1        $ft4, 0x40($sp)
/* EBD404 801A5754 3C013FC0 */  lui         $at, (0x3FC00000 >> 16)
/* EBD408 801A5758 24180028 */  addiu       $t8, $zero, 0x28
/* EBD40C 801A575C E6100020 */  swc1        $ft4, 0x20($s0)
/* EBD410 801A5760 C7B20044 */  lwc1        $ft5, 0x44($sp)
/* EBD414 801A5764 E6120024 */  swc1        $ft5, 0x24($s0)
/* EBD418 801A5768 C7A40048 */  lwc1        $ft0, 0x48($sp)
/* EBD41C 801A576C E6040028 */  swc1        $ft0, 0x28($s0)
/* EBD420 801A5770 C7A80034 */  lwc1        $ft2, 0x34($sp)
/* EBD424 801A5774 C6260074 */  lwc1        $ft1, 0x74($s1)
/* EBD428 801A5778 46083280 */  add.s       $ft3, $ft1, $ft2
/* EBD42C 801A577C E60A0004 */  swc1        $ft3, 0x4($s0)
/* EBD430 801A5780 C7B20038 */  lwc1        $ft5, 0x38($sp)
/* EBD434 801A5784 C6300078 */  lwc1        $ft4, 0x78($s1)
/* EBD438 801A5788 46128100 */  add.s       $ft0, $ft4, $ft5
/* EBD43C 801A578C E6040008 */  swc1        $ft0, 0x8($s0)
/* EBD440 801A5790 C7A8003C */  lwc1        $ft2, 0x3C($sp)
/* EBD444 801A5794 C626007C */  lwc1        $ft1, 0x7C($s1)
/* EBD448 801A5798 46083280 */  add.s       $ft3, $ft1, $ft2
/* EBD44C 801A579C E60A000C */  swc1        $ft3, 0xC($s0)
/* EBD450 801A57A0 C7B0004C */  lwc1        $ft4, 0x4C($sp)
/* EBD454 801A57A4 E6100010 */  swc1        $ft4, 0x10($s0)
/* EBD458 801A57A8 C7B20050 */  lwc1        $ft5, 0x50($sp)
/* EBD45C 801A57AC E6120014 */  swc1        $ft5, 0x14($s0)
/* EBD460 801A57B0 C7A40054 */  lwc1        $ft0, 0x54($sp)
/* EBD464 801A57B4 E6040018 */  swc1        $ft0, 0x18($s0)
/* EBD468 801A57B8 C626017C */  lwc1        $ft1, 0x17C($s1)
/* EBD46C 801A57BC 44812000 */  mtc1        $at, $ft0
/* EBD470 801A57C0 E6060048 */  swc1        $ft1, 0x48($s0)
/* EBD474 801A57C4 C6280180 */  lwc1        $ft2, 0x180($s1)
/* EBD478 801A57C8 E608004C */  swc1        $ft2, 0x4C($s0)
/* EBD47C 801A57CC C62A0004 */  lwc1        $ft3, 0x4($s1)
/* EBD480 801A57D0 E60A0050 */  swc1        $ft3, 0x50($s0)
/* EBD484 801A57D4 C6300000 */  lwc1        $ft4, 0x0($s1)
/* EBD488 801A57D8 E6100054 */  swc1        $ft4, 0x54($s0)
/* EBD48C 801A57DC C63200EC */  lwc1        $ft5, 0xEC($s1)
/* EBD490 801A57E0 AE000060 */  sw          $zero, 0x60($s0)
/* EBD494 801A57E4 E6120018 */  swc1        $ft5, 0x18($s0)
/* EBD498 801A57E8 8FAF006C */  lw          $t7, 0x6C($sp)
/* EBD49C 801A57EC AE180064 */  sw          $t8, 0x64($s0)
/* EBD4A0 801A57F0 E6040044 */  swc1        $ft0, 0x44($s0)
/* EBD4A4 801A57F4 A60F0002 */  sh          $t7, 0x2($s0)
/* EBD4A8 801A57F8 8E3901C4 */  lw          $t9, 0x1C4($s1)
/* EBD4AC 801A57FC AE190068 */  sw          $t9, 0x68($s0)
/* EBD4B0 801A5800 8FBF002C */  lw          $ra, 0x2C($sp)
/* EBD4B4 801A5804 D7B40018 */  ldc1        $fs0, 0x18($sp)
/* EBD4B8 801A5808 8FB00020 */  lw          $s0, 0x20($sp)
/* EBD4BC 801A580C 8FB10024 */  lw          $s1, 0x24($sp)
/* EBD4C0 801A5810 8FB20028 */  lw          $s2, 0x28($sp)
/* EBD4C4 801A5814 03E00008 */  jr          $ra
/* EBD4C8 801A5818 27BD0058 */   addiu      $sp, $sp, 0x58
glabel func_i6_801A581C
/* EBD4CC 801A581C 27BDFFD0 */  addiu       $sp, $sp, -0x30
/* EBD4D0 801A5820 44856000 */  mtc1        $a1, $fa0
/* EBD4D4 801A5824 AFBF002C */  sw          $ra, 0x2C($sp)
/* EBD4D8 801A5828 AFB00028 */  sw          $s0, 0x28($sp)
/* EBD4DC 801A582C 3C108017 */  lui         $s0, %hi(gPlayerShots)
/* EBD4E0 801A5830 3C028017 */  lui         $v0, %hi(gUnkEntities30)
/* EBD4E4 801A5834 24424750 */  addiu       $v0, $v0, %lo(gUnkEntities30)
/* EBD4E8 801A5838 26104050 */  addiu       $s0, $s0, %lo(gPlayerShots)
/* EBD4EC 801A583C 920E0000 */  lbu         $t6, 0x0($s0)
.Li6_801A5840:
/* EBD4F0 801A5840 15C00011 */  bnez        $t6, .Li6_801A5888
/* EBD4F4 801A5844 3C014348 */   lui        $at, (0x43480000 >> 16)
/* EBD4F8 801A5848 44812000 */  mtc1        $at, $ft0
/* EBD4FC 801A584C 3C0142C8 */  lui         $at, (0x42C80000 >> 16)
/* EBD500 801A5850 44813000 */  mtc1        $at, $ft1
/* EBD504 801A5854 44066000 */  mfc1        $a2, $fa0
/* EBD508 801A5858 240F0009 */  addiu       $t7, $zero, 0x9
/* EBD50C 801A585C AFAF0014 */  sw          $t7, 0x14($sp)
/* EBD510 801A5860 02002825 */  or          $a1, $s0, $zero
/* EBD514 801A5864 3C07C2C8 */  lui         $a3, (0xC2C80000 >> 16)
/* EBD518 801A5868 E7A40010 */  swc1        $ft0, 0x10($sp)
/* EBD51C 801A586C 0C069558 */  jal         func_i6_801A5560
/* EBD520 801A5870 E7A60018 */   swc1       $ft1, 0x18($sp)
/* EBD524 801A5874 26040038 */  addiu       $a0, $s0, 0x38
/* EBD528 801A5878 0C02980A */  jal         func_800A6028
/* EBD52C 801A587C 3C050900 */   lui        $a1, (0x9000000 >> 16)
/* EBD530 801A5880 10000005 */  b           .Li6_801A5898
/* EBD534 801A5884 8FBF002C */   lw         $ra, 0x2C($sp)
.Li6_801A5888:
/* EBD538 801A5888 26100070 */  addiu       $s0, $s0, 0x70
/* EBD53C 801A588C 5602FFEC */  bnel        $s0, $v0, .Li6_801A5840
/* EBD540 801A5890 920E0000 */   lbu        $t6, 0x0($s0)
/* EBD544 801A5894 8FBF002C */  lw          $ra, 0x2C($sp)
.Li6_801A5898:
/* EBD548 801A5898 8FB00028 */  lw          $s0, 0x28($sp)
/* EBD54C 801A589C 27BD0030 */  addiu       $sp, $sp, 0x30
/* EBD550 801A58A0 03E00008 */  jr          $ra
/* EBD554 801A58A4 00000000 */   nop
glabel func_i6_801A58A8
/* EBD558 801A58A8 27BDFFE8 */  addiu       $sp, $sp, -0x18
/* EBD55C 801A58AC AFBF0014 */  sw          $ra, 0x14($sp)
/* EBD560 801A58B0 241F0006 */  addiu       $ra, $zero, 0x6
/* EBD564 801A58B4 00803025 */  or          $a2, $a0, $zero
/* EBD568 801A58B8 8CCE01C4 */  lw          $t6, 0x1C4($a2)
/* EBD56C 801A58BC 3C0F800E */  lui         $t7, %hi(gControllerPress)
/* EBD570 801A58C0 01DF0019 */  multu       $t6, $ra
/* EBD574 801A58C4 3C0E800E */  lui         $t6, %hi(gControllerHold)
/* EBD578 801A58C8 00001012 */  mflo        $v0
/* EBD57C 801A58CC 01E27821 */  addu        $t7, $t7, $v0
/* EBD580 801A58D0 95EFD898 */  lhu         $t7, %lo(gControllerPress)($t7)
/* EBD584 801A58D4 31F88000 */  andi        $t8, $t7, 0x8000
/* EBD588 801A58D8 53000007 */  beql        $t8, $zero, .Li6_801A58F8
/* EBD58C 801A58DC 01C27021 */   addu       $t6, $t6, $v0
/* EBD590 801A58E0 8CC201C4 */  lw          $v0, 0x1C4($a2)
/* EBD594 801A58E4 ACC00244 */  sw          $zero, 0x244($a2)
/* EBD598 801A58E8 0002C880 */  sll         $t9, $v0, 2
/* EBD59C 801A58EC 0322C823 */  subu        $t9, $t9, $v0
/* EBD5A0 801A58F0 00191040 */  sll         $v0, $t9, 1
/* EBD5A4 801A58F4 01C27021 */  addu        $t6, $t6, $v0
.Li6_801A58F8:
/* EBD5A8 801A58F8 95CED880 */  lhu         $t6, %lo(gControllerHold)($t6)
/* EBD5AC 801A58FC 31CF8000 */  andi        $t7, $t6, 0x8000
/* EBD5B0 801A5900 51E00019 */  beql        $t7, $zero, .Li6_801A5968
/* EBD5B4 801A5904 8CC201BC */   lw         $v0, 0x1BC($a2)
/* EBD5B8 801A5908 8CC20244 */  lw          $v0, 0x244($a2)
/* EBD5BC 801A590C 00C02025 */  or          $a0, $a2, $zero
/* EBD5C0 801A5910 3C05C2C8 */  lui         $a1, (0xC2C80000 >> 16)
/* EBD5C4 801A5914 5440000F */  bnel        $v0, $zero, .Li6_801A5954
/* EBD5C8 801A5918 24590001 */   addiu      $t9, $v0, 0x1
/* EBD5CC 801A591C 0C069607 */  jal         func_i6_801A581C
/* EBD5D0 801A5920 AFA60018 */   sw         $a2, 0x18($sp)
/* EBD5D4 801A5924 3C0142C8 */  lui         $at, (0x42C80000 >> 16)
/* EBD5D8 801A5928 44811000 */  mtc1        $at, $fv1
/* EBD5DC 801A592C 8FA40018 */  lw          $a0, 0x18($sp)
/* EBD5E0 801A5930 44051000 */  mfc1        $a1, $fv1
/* EBD5E4 801A5934 0C069607 */  jal         func_i6_801A581C
/* EBD5E8 801A5938 00000000 */   nop
/* EBD5EC 801A593C 8FA60018 */  lw          $a2, 0x18($sp)
/* EBD5F0 801A5940 2418001E */  addiu       $t8, $zero, 0x1E
/* EBD5F4 801A5944 241F0006 */  addiu       $ra, $zero, 0x6
/* EBD5F8 801A5948 ACD801BC */  sw          $t8, 0x1BC($a2)
/* EBD5FC 801A594C 8CC20244 */  lw          $v0, 0x244($a2)
/* EBD600 801A5950 24590001 */  addiu       $t9, $v0, 0x1
.Li6_801A5954:
/* EBD604 801A5954 2B210004 */  slti        $at, $t9, 0x4
/* EBD608 801A5958 14200002 */  bnez        $at, .Li6_801A5964
/* EBD60C 801A595C ACD90244 */   sw         $t9, 0x244($a2)
/* EBD610 801A5960 ACC00244 */  sw          $zero, 0x244($a2)
.Li6_801A5964:
/* EBD614 801A5964 8CC201BC */  lw          $v0, 0x1BC($a2)
.Li6_801A5968:
/* EBD618 801A5968 3C0142C8 */  lui         $at, (0x42C80000 >> 16)
/* EBD61C 801A596C 44811000 */  mtc1        $at, $fv1
/* EBD620 801A5970 18400003 */  blez        $v0, .Li6_801A5980
/* EBD624 801A5974 244FFFFC */   addiu      $t7, $v0, -0x4
/* EBD628 801A5978 10000002 */  b           .Li6_801A5984
/* EBD62C 801A597C ACCF01BC */   sw         $t7, 0x1BC($a2)
.Li6_801A5980:
/* EBD630 801A5980 ACC001BC */  sw          $zero, 0x1BC($a2)
.Li6_801A5984:
/* EBD634 801A5984 8CD801C4 */  lw          $t8, 0x1C4($a2)
/* EBD638 801A5988 3C0E800E */  lui         $t6, %hi(gControllerPress)
/* EBD63C 801A598C 3C038016 */  lui         $v1, %hi(gActors)
/* EBD640 801A5990 031F0019 */  multu       $t8, $ra
/* EBD644 801A5994 3C0A8017 */  lui         $t2, %hi(gUnkEntities30)
/* EBD648 801A5998 254A4750 */  addiu       $t2, $t2, %lo(gUnkEntities30)
/* EBD64C 801A599C 24633FE0 */  addiu       $v1, $v1, %lo(gActors)
/* EBD650 801A59A0 3C013F80 */  lui         $at, (0x3F800000 >> 16)
/* EBD654 801A59A4 240D0002 */  addiu       $t5, $zero, 0x2
/* EBD658 801A59A8 240C0003 */  addiu       $t4, $zero, 0x3
/* EBD65C 801A59AC 240B0030 */  addiu       $t3, $zero, 0x30
/* EBD660 801A59B0 240900C8 */  addiu       $t1, $zero, 0xC8
/* EBD664 801A59B4 24080002 */  addiu       $t0, $zero, 0x2
/* EBD668 801A59B8 0000C812 */  mflo        $t9
/* EBD66C 801A59BC 01D97021 */  addu        $t6, $t6, $t9
/* EBD670 801A59C0 95CED898 */  lhu         $t6, %lo(gControllerPress)($t6)
/* EBD674 801A59C4 31CF0010 */  andi        $t7, $t6, 0x10
/* EBD678 801A59C8 51E00003 */  beql        $t7, $zero, .Li6_801A59D8
/* EBD67C 801A59CC 8CC701C0 */   lw         $a3, 0x1C0($a2)
/* EBD680 801A59D0 ACC001C0 */  sw          $zero, 0x1C0($a2)
/* EBD684 801A59D4 8CC701C0 */  lw          $a3, 0x1C0($a2)
.Li6_801A59D8:
/* EBD688 801A59D8 00002825 */  or          $a1, $zero, $zero
/* EBD68C 801A59DC 58E00026 */  blezl       $a3, .Li6_801A5A78
/* EBD690 801A59E0 8CCF01C4 */   lw         $t7, 0x1C4($a2)
/* EBD694 801A59E4 44810000 */  mtc1        $at, $fv0
/* EBD698 801A59E8 240400FF */  addiu       $a0, $zero, 0xFF
.Li6_801A59EC:
/* EBD69C 801A59EC 90780000 */  lbu         $t8, 0x0($v1)
/* EBD6A0 801A59F0 5518001D */  bnel        $t0, $t8, .Li6_801A5A68
/* EBD6A4 801A59F4 24A50001 */   addiu      $a1, $a1, 0x1
/* EBD6A8 801A59F8 94790002 */  lhu         $t9, 0x2($v1)
/* EBD6AC 801A59FC 5539001A */  bnel        $t1, $t9, .Li6_801A5A68
/* EBD6B0 801A5A00 24A50001 */   addiu      $a1, $a1, 0x1
/* EBD6B4 801A5A04 00AB0019 */  multu       $a1, $t3
/* EBD6B8 801A5A08 C4700004 */  lwc1        $ft4, 0x4($v1)
/* EBD6BC 801A5A0C C4720008 */  lwc1        $ft5, 0x8($v1)
/* EBD6C0 801A5A10 00007012 */  mflo        $t6
/* EBD6C4 801A5A14 014E1021 */  addu        $v0, $t2, $t6
/* EBD6C8 801A5A18 A04C0000 */  sb          $t4, 0x0($v0)
/* EBD6CC 801A5A1C E4400024 */  swc1        $fv0, 0x24($v0)
/* EBD6D0 801A5A20 C4C40074 */  lwc1        $ft0, 0x74($a2)
/* EBD6D4 801A5A24 E4440004 */  swc1        $ft0, 0x4($v0)
/* EBD6D8 801A5A28 C4C60078 */  lwc1        $ft1, 0x78($a2)
/* EBD6DC 801A5A2C C464000C */  lwc1        $ft0, 0xC($v1)
/* EBD6E0 801A5A30 E4460008 */  swc1        $ft1, 0x8($v0)
/* EBD6E4 801A5A34 C4C8007C */  lwc1        $ft2, 0x7C($a2)
/* EBD6E8 801A5A38 A44D0002 */  sh          $t5, 0x2($v0)
/* EBD6EC 801A5A3C A044002C */  sb          $a0, 0x2C($v0)
/* EBD6F0 801A5A40 46024281 */  sub.s       $ft3, $ft2, $fv1
/* EBD6F4 801A5A44 A044002D */  sb          $a0, 0x2D($v0)
/* EBD6F8 801A5A48 A044002E */  sb          $a0, 0x2E($v0)
/* EBD6FC 801A5A4C A044002F */  sb          $a0, 0x2F($v0)
/* EBD700 801A5A50 E44A000C */  swc1        $ft3, 0xC($v0)
/* EBD704 801A5A54 E4500010 */  swc1        $ft4, 0x10($v0)
/* EBD708 801A5A58 E4520014 */  swc1        $ft5, 0x14($v0)
/* EBD70C 801A5A5C E4440018 */  swc1        $ft0, 0x18($v0)
/* EBD710 801A5A60 8CC701C0 */  lw          $a3, 0x1C0($a2)
/* EBD714 801A5A64 24A50001 */  addiu       $a1, $a1, 0x1
.Li6_801A5A68:
/* EBD718 801A5A68 00A7082A */  slt         $at, $a1, $a3
/* EBD71C 801A5A6C 1420FFDF */  bnez        $at, .Li6_801A59EC
/* EBD720 801A5A70 246302F4 */   addiu      $v1, $v1, 0x2F4
/* EBD724 801A5A74 8CCF01C4 */  lw          $t7, 0x1C4($a2)
.Li6_801A5A78:
/* EBD728 801A5A78 3C19800E */  lui         $t9, %hi(gControllerHold)
/* EBD72C 801A5A7C 01FF0019 */  multu       $t7, $ra
/* EBD730 801A5A80 24EF0001 */  addiu       $t7, $a3, 0x1
/* EBD734 801A5A84 01E03825 */  or          $a3, $t7, $zero
/* EBD738 801A5A88 29E1003D */  slti        $at, $t7, 0x3D
/* EBD73C 801A5A8C 0000C012 */  mflo        $t8
/* EBD740 801A5A90 0338C821 */  addu        $t9, $t9, $t8
/* EBD744 801A5A94 9739D880 */  lhu         $t9, %lo(gControllerHold)($t9)
/* EBD748 801A5A98 332E0010 */  andi        $t6, $t9, 0x10
/* EBD74C 801A5A9C 51C00009 */  beql        $t6, $zero, .Li6_801A5AC4
/* EBD750 801A5AA0 ACC001C0 */   sw         $zero, 0x1C0($a2)
/* EBD754 801A5AA4 14200004 */  bnez        $at, .Li6_801A5AB8
/* EBD758 801A5AA8 ACCF01C0 */   sw         $t7, 0x1C0($a2)
/* EBD75C 801A5AAC 2418003C */  addiu       $t8, $zero, 0x3C
/* EBD760 801A5AB0 10000004 */  b           .Li6_801A5AC4
/* EBD764 801A5AB4 ACD801C0 */   sw         $t8, 0x1C0($a2)
.Li6_801A5AB8:
/* EBD768 801A5AB8 10000002 */  b           .Li6_801A5AC4
/* EBD76C 801A5ABC ACC701C0 */   sw         $a3, 0x1C0($a2)
/* EBD770 801A5AC0 ACC001C0 */  sw          $zero, 0x1C0($a2)
.Li6_801A5AC4:
/* EBD774 801A5AC4 8FBF0014 */  lw          $ra, 0x14($sp)
/* EBD778 801A5AC8 27BD0018 */  addiu       $sp, $sp, 0x18
/* EBD77C 801A5ACC 03E00008 */  jr          $ra
/* EBD780 801A5AD0 00000000 */   nop
.section .late_rodata
dlabel D_i6_801A7ED4
/* EBFB84 801A7ED4 3EB33334 */ .float 0.3500000238

dlabel D_i6_801A7ED8
/* EBFB88 801A7ED8 3727C5AC */ .float 9.999999747e-06

dlabel D_i6_801A7EDC
/* EBFB8C 801A7EDC 3E99999A */ .float 0.3000000119

dlabel D_i6_801A7EE0
/* EBFB90 801A7EE0 3727C5AC */ .float 9.999999747e-06

dlabel D_i6_801A7EE4
/* EBFB94 801A7EE4 3727C5AC */ .float 9.999999747e-06

dlabel D_i6_801A7EE8
/* EBFB98 801A7EE8 3727C5AC */ .float 9.999999747e-06


.section .text
/* Generated by spimdisasm 1.19.1.dev0 */

glabel func_i6_801A5AD4
/* EBD784 801A5AD4 27BDFFD0 */  addiu       $sp, $sp, -0x30
/* EBD788 801A5AD8 AFB00020 */  sw          $s0, 0x20($sp)
/* EBD78C 801A5ADC 00808025 */  or          $s0, $a0, $zero
/* EBD790 801A5AE0 AFBF0024 */  sw          $ra, 0x24($sp)
/* EBD794 801A5AE4 8E0E01B4 */  lw          $t6, 0x1B4($s0)
/* EBD798 801A5AE8 3C188016 */  lui         $t8, %hi(gActors)
/* EBD79C 801A5AEC 27183FE0 */  addiu       $t8, $t8, %lo(gActors)
/* EBD7A0 801A5AF0 000E7880 */  sll         $t7, $t6, 2
/* EBD7A4 801A5AF4 01EE7823 */  subu        $t7, $t7, $t6
/* EBD7A8 801A5AF8 000F7900 */  sll         $t7, $t7, 4
/* EBD7AC 801A5AFC 01EE7823 */  subu        $t7, $t7, $t6
/* EBD7B0 801A5B00 000F7880 */  sll         $t7, $t7, 2
/* EBD7B4 801A5B04 01EE7821 */  addu        $t7, $t7, $t6
/* EBD7B8 801A5B08 000F7880 */  sll         $t7, $t7, 2
/* EBD7BC 801A5B0C 01F81021 */  addu        $v0, $t7, $t8
/* EBD7C0 801A5B10 C4440004 */  lwc1        $ft0, 0x4($v0)
/* EBD7C4 801A5B14 8E0301B0 */  lw          $v1, 0x1B0($s0)
/* EBD7C8 801A5B18 E6040074 */  swc1        $ft0, 0x74($s0)
/* EBD7CC 801A5B1C C4460008 */  lwc1        $ft1, 0x8($v0)
/* EBD7D0 801A5B20 28610002 */  slti        $at, $v1, 0x2
/* EBD7D4 801A5B24 E6060078 */  swc1        $ft1, 0x78($s0)
/* EBD7D8 801A5B28 C448000C */  lwc1        $ft2, 0xC($v0)
/* EBD7DC 801A5B2C E608007C */  swc1        $ft2, 0x7C($s0)
/* EBD7E0 801A5B30 C44A0014 */  lwc1        $ft3, 0x14($v0)
/* EBD7E4 801A5B34 E60A0000 */  swc1        $ft3, 0x0($s0)
/* EBD7E8 801A5B38 C4500010 */  lwc1        $ft4, 0x10($v0)
/* EBD7EC 801A5B3C E6100004 */  swc1        $ft4, 0x4($s0)
/* EBD7F0 801A5B40 C4520018 */  lwc1        $ft5, 0x18($v0)
/* EBD7F4 801A5B44 10200014 */  beqz        $at, .Li6_801A5B98
/* EBD7F8 801A5B48 E61200EC */   swc1       $ft5, 0xEC($s0)
/* EBD7FC 801A5B4C 14600005 */  bnez        $v1, .Li6_801A5B64
/* EBD800 801A5B50 3C02800E */   lui        $v0, %hi(gControllerLock)
/* EBD804 801A5B54 241900C8 */  addiu       $t9, $zero, 0xC8
/* EBD808 801A5B58 24680001 */  addiu       $t0, $v1, 0x1
/* EBD80C 801A5B5C AE1901BC */  sw          $t9, 0x1BC($s0)
/* EBD810 801A5B60 AE0801B0 */  sw          $t0, 0x1B0($s0)
.Li6_801A5B64:
/* EBD814 801A5B64 2442D8B4 */  addiu       $v0, $v0, %lo(gControllerLock)
/* EBD818 801A5B68 2409000A */  addiu       $t1, $zero, 0xA
/* EBD81C 801A5B6C AC490000 */  sw          $t1, 0x0($v0)
/* EBD820 801A5B70 8E0A01BC */  lw          $t2, 0x1BC($s0)
/* EBD824 801A5B74 55400009 */  bnel        $t2, $zero, .Li6_801A5B9C
/* EBD828 801A5B78 8E0E01C4 */   lw         $t6, 0x1C4($s0)
/* EBD82C 801A5B7C AC400000 */  sw          $zero, 0x0($v0)
/* EBD830 801A5B80 8E0B01B0 */  lw          $t3, 0x1B0($s0)
/* EBD834 801A5B84 240D0032 */  addiu       $t5, $zero, 0x32
/* EBD838 801A5B88 3C018017 */  lui         $at, %hi(D_80177838)
/* EBD83C 801A5B8C 256C0001 */  addiu       $t4, $t3, 0x1
/* EBD840 801A5B90 AE0C01B0 */  sw          $t4, 0x1B0($s0)
/* EBD844 801A5B94 AC2D7838 */  sw          $t5, %lo(D_80177838)($at)
.Li6_801A5B98:
/* EBD848 801A5B98 8E0E01C4 */  lw          $t6, 0x1C4($s0)
.Li6_801A5B9C:
/* EBD84C 801A5B9C 3C18800E */  lui         $t8, %hi(gControllerPress)
/* EBD850 801A5BA0 2718D898 */  addiu       $t8, $t8, %lo(gControllerPress)
/* EBD854 801A5BA4 000E7880 */  sll         $t7, $t6, 2
/* EBD858 801A5BA8 01EE7823 */  subu        $t7, $t7, $t6
/* EBD85C 801A5BAC 000F7840 */  sll         $t7, $t7, 1
/* EBD860 801A5BB0 01F81021 */  addu        $v0, $t7, $t8
/* EBD864 801A5BB4 80590002 */  lb          $t9, 0x2($v0)
/* EBD868 801A5BB8 3C014000 */  lui         $at, (0x40000000 >> 16)
/* EBD86C 801A5BBC 44817000 */  mtc1        $at, $fa1
/* EBD870 801A5BC0 44992000 */  mtc1        $t9, $ft0
/* EBD874 801A5BC4 80480003 */  lb          $t0, 0x3($v0)
/* EBD878 801A5BC8 3C01801A */  lui         $at, %hi(D_i6_801A7ED4)
/* EBD87C 801A5BCC 468020A0 */  cvt.s.w     $fv1, $ft0
/* EBD880 801A5BD0 C42A7ED4 */  lwc1        $ft3, %lo(D_i6_801A7ED4)($at)
/* EBD884 801A5BD4 44883000 */  mtc1        $t0, $ft1
/* EBD888 801A5BD8 3C01801A */  lui         $at, %hi(D_i6_801A7ED8)
/* EBD88C 801A5BDC C4327ED8 */  lwc1        $ft5, %lo(D_i6_801A7ED8)($at)
/* EBD890 801A5BE0 46803320 */  cvt.s.w     $fa0, $ft1
/* EBD894 801A5BE4 44077000 */  mfc1        $a3, $fa1
/* EBD898 801A5BE8 E7A2002C */  swc1        $fv1, 0x2C($sp)
/* EBD89C 801A5BEC 260400E8 */  addiu       $a0, $s0, 0xE8
/* EBD8A0 801A5BF0 3C063F00 */  lui         $a2, (0x3F000000 >> 16)
/* EBD8A4 801A5BF4 46001207 */  neg.s       $ft2, $fv1
/* EBD8A8 801A5BF8 46006307 */  neg.s       $fa0, $fa0
/* EBD8AC 801A5BFC 460A4402 */  mul.s       $ft4, $ft2, $ft3
/* EBD8B0 801A5C00 E7AC0028 */  swc1        $fa0, 0x28($sp)
/* EBD8B4 801A5C04 E7B20010 */  swc1        $ft5, 0x10($sp)
/* EBD8B8 801A5C08 44058000 */  mfc1        $a1, $ft4
/* EBD8BC 801A5C0C 0C026F0B */  jal         Math_SmoothStepToF
/* EBD8C0 801A5C10 00000000 */   nop
/* EBD8C4 801A5C14 3C014000 */  lui         $at, (0x40000000 >> 16)
/* EBD8C8 801A5C18 44817000 */  mtc1        $at, $fa1
/* EBD8CC 801A5C1C C7AC0028 */  lwc1        $fa0, 0x28($sp)
/* EBD8D0 801A5C20 3C01801A */  lui         $at, %hi(D_i6_801A7EDC)
/* EBD8D4 801A5C24 C4267EDC */  lwc1        $ft1, %lo(D_i6_801A7EDC)($at)
/* EBD8D8 801A5C28 46006107 */  neg.s       $ft0, $fa0
/* EBD8DC 801A5C2C 3C01801A */  lui         $at, %hi(D_i6_801A7EE0)
/* EBD8E0 801A5C30 46062202 */  mul.s       $ft2, $ft0, $ft1
/* EBD8E4 801A5C34 C42A7EE0 */  lwc1        $ft3, %lo(D_i6_801A7EE0)($at)
/* EBD8E8 801A5C38 44077000 */  mfc1        $a3, $fa1
/* EBD8EC 801A5C3C 260400E4 */  addiu       $a0, $s0, 0xE4
/* EBD8F0 801A5C40 3C063F00 */  lui         $a2, (0x3F000000 >> 16)
/* EBD8F4 801A5C44 E7AA0010 */  swc1        $ft3, 0x10($sp)
/* EBD8F8 801A5C48 44054000 */  mfc1        $a1, $ft2
/* EBD8FC 801A5C4C 0C026F0B */  jal         Math_SmoothStepToF
/* EBD900 801A5C50 00000000 */   nop
/* EBD904 801A5C54 8E0901B4 */  lw          $t1, 0x1B4($s0)
/* EBD908 801A5C58 C610007C */  lwc1        $ft4, 0x7C($s0)
/* EBD90C 801A5C5C 3C014000 */  lui         $at, (0x40000000 >> 16)
/* EBD910 801A5C60 00095080 */  sll         $t2, $t1, 2
/* EBD914 801A5C64 01495023 */  subu        $t2, $t2, $t1
/* EBD918 801A5C68 000A5100 */  sll         $t2, $t2, 4
/* EBD91C 801A5C6C 01495023 */  subu        $t2, $t2, $t1
/* EBD920 801A5C70 000A5080 */  sll         $t2, $t2, 2
/* EBD924 801A5C74 44817000 */  mtc1        $at, $fa1
/* EBD928 801A5C78 01495021 */  addu        $t2, $t2, $t1
/* EBD92C 801A5C7C C7A2002C */  lwc1        $fv1, 0x2C($sp)
/* EBD930 801A5C80 C7AC0028 */  lwc1        $fa0, 0x28($sp)
/* EBD934 801A5C84 000A5080 */  sll         $t2, $t2, 2
/* EBD938 801A5C88 3C018016 */  lui         $at, %hi(gActors + 0xF0)
/* EBD93C 801A5C8C 002A0821 */  addu        $at, $at, $t2
/* EBD940 801A5C90 E6100138 */  swc1        $ft4, 0x138($s0)
/* EBD944 801A5C94 C43240D0 */  lwc1        $ft5, %lo(gActors + 0xF0)($at)
/* EBD948 801A5C98 C6060144 */  lwc1        $ft1, 0x144($s0)
/* EBD94C 801A5C9C 3C018017 */  lui         $at, %hi(D_80177D08)
/* EBD950 801A5CA0 46009107 */  neg.s       $ft0, $ft5
/* EBD954 801A5CA4 24030006 */  addiu       $v1, $zero, 0x6
/* EBD958 801A5CA8 E6040140 */  swc1        $ft0, 0x140($s0)
/* EBD95C 801A5CAC C6000140 */  lwc1        $fv0, 0x140($s0)
/* EBD960 801A5CB0 3C02800E */  lui         $v0, %hi(gControllerHold)
/* EBD964 801A5CB4 26040180 */  addiu       $a0, $s0, 0x180
/* EBD968 801A5CB8 46003200 */  add.s       $ft2, $ft1, $fv0
/* EBD96C 801A5CBC 3C063F00 */  lui         $a2, (0x3F000000 >> 16)
/* EBD970 801A5CC0 E6080144 */  swc1        $ft2, 0x144($s0)
/* EBD974 801A5CC4 E4207D08 */  swc1        $fv0, %lo(D_80177D08)($at)
/* EBD978 801A5CC8 C60A0144 */  lwc1        $ft3, 0x144($s0)
/* EBD97C 801A5CCC 3C018017 */  lui         $at, %hi(D_80177D20)
/* EBD980 801A5CD0 E42A7D20 */  swc1        $ft3, %lo(D_80177D20)($at)
/* EBD984 801A5CD4 8E0B01C4 */  lw          $t3, 0x1C4($s0)
/* EBD988 801A5CD8 01630019 */  multu       $t3, $v1
/* EBD98C 801A5CDC 00006012 */  mflo        $t4
/* EBD990 801A5CE0 004C1021 */  addu        $v0, $v0, $t4
/* EBD994 801A5CE4 9442D880 */  lhu         $v0, %lo(gControllerHold)($v0)
/* EBD998 801A5CE8 304D2000 */  andi        $t5, $v0, 0x2000
/* EBD99C 801A5CEC 55A00051 */  bnel        $t5, $zero, .Li6_801A5E34
/* EBD9A0 801A5CF0 3C0141F0 */   lui        $at, (0x41F00000 >> 16)
/* EBD9A4 801A5CF4 46021402 */  mul.s       $ft4, $fv1, $fv1
/* EBD9A8 801A5CF8 3C01425C */  lui         $at, (0x425C0000 >> 16)
/* EBD9AC 801A5CFC 44812000 */  mtc1        $at, $ft0
/* EBD9B0 801A5D00 460C6482 */  mul.s       $ft5, $fa0, $fa0
/* EBD9B4 801A5D04 304E0001 */  andi        $t6, $v0, 0x1
/* EBD9B8 801A5D08 46128000 */  add.s       $fv0, $ft4, $ft5
/* EBD9BC 801A5D0C 46000004 */  sqrt.s      $fv0, $fv0
/* EBD9C0 801A5D10 4600203C */  c.lt.s      $ft0, $fv0
/* EBD9C4 801A5D14 00000000 */  nop
/* EBD9C8 801A5D18 45020046 */  bc1fl       .Li6_801A5E34
/* EBD9CC 801A5D1C 3C0141F0 */   lui        $at, (0x41F00000 >> 16)
/* EBD9D0 801A5D20 15C00007 */  bnez        $t6, .Li6_801A5D40
/* EBD9D4 801A5D24 3C014220 */   lui        $at, (0x42200000 >> 16)
/* EBD9D8 801A5D28 44813000 */  mtc1        $at, $ft1
/* EBD9DC 801A5D2C 00000000 */  nop
/* EBD9E0 801A5D30 4602303C */  c.lt.s      $ft1, $fv1
/* EBD9E4 801A5D34 00000000 */  nop
/* EBD9E8 801A5D38 4502000C */  bc1fl       .Li6_801A5D6C
/* EBD9EC 801A5D3C 30590002 */   andi       $t9, $v0, 0x2
.Li6_801A5D40:
/* EBD9F0 801A5D40 C6080008 */  lwc1        $ft2, 0x8($s0)
/* EBD9F4 801A5D44 8E0F01C4 */  lw          $t7, 0x1C4($s0)
/* EBD9F8 801A5D48 3C02800E */  lui         $v0, %hi(gControllerHold)
/* EBD9FC 801A5D4C 460E4280 */  add.s       $ft3, $ft2, $fa1
/* EBDA00 801A5D50 000FC080 */  sll         $t8, $t7, 2
/* EBDA04 801A5D54 030FC023 */  subu        $t8, $t8, $t7
/* EBDA08 801A5D58 0018C040 */  sll         $t8, $t8, 1
/* EBDA0C 801A5D5C 00581021 */  addu        $v0, $v0, $t8
/* EBDA10 801A5D60 E60A0008 */  swc1        $ft3, 0x8($s0)
/* EBDA14 801A5D64 9442D880 */  lhu         $v0, %lo(gControllerHold)($v0)
/* EBDA18 801A5D68 30590002 */  andi        $t9, $v0, 0x2
.Li6_801A5D6C:
/* EBDA1C 801A5D6C 17200007 */  bnez        $t9, .Li6_801A5D8C
/* EBDA20 801A5D70 3C01C220 */   lui        $at, (0xC2200000 >> 16)
/* EBDA24 801A5D74 44818000 */  mtc1        $at, $ft4
/* EBDA28 801A5D78 00000000 */  nop
/* EBDA2C 801A5D7C 4610103C */  c.lt.s      $fv1, $ft4
/* EBDA30 801A5D80 00000000 */  nop
/* EBDA34 801A5D84 4502000C */  bc1fl       .Li6_801A5DB8
/* EBDA38 801A5D88 304A0008 */   andi       $t2, $v0, 0x8
.Li6_801A5D8C:
/* EBDA3C 801A5D8C C6120008 */  lwc1        $ft5, 0x8($s0)
/* EBDA40 801A5D90 8E0801C4 */  lw          $t0, 0x1C4($s0)
/* EBDA44 801A5D94 3C02800E */  lui         $v0, %hi(gControllerHold)
/* EBDA48 801A5D98 460E9101 */  sub.s       $ft0, $ft5, $fa1
/* EBDA4C 801A5D9C 00084880 */  sll         $t1, $t0, 2
/* EBDA50 801A5DA0 01284823 */  subu        $t1, $t1, $t0
/* EBDA54 801A5DA4 00094840 */  sll         $t1, $t1, 1
/* EBDA58 801A5DA8 00491021 */  addu        $v0, $v0, $t1
/* EBDA5C 801A5DAC E6040008 */  swc1        $ft0, 0x8($s0)
/* EBDA60 801A5DB0 9442D880 */  lhu         $v0, %lo(gControllerHold)($v0)
/* EBDA64 801A5DB4 304A0008 */  andi        $t2, $v0, 0x8
.Li6_801A5DB8:
/* EBDA68 801A5DB8 15400007 */  bnez        $t2, .Li6_801A5DD8
/* EBDA6C 801A5DBC 3C01C220 */   lui        $at, (0xC2200000 >> 16)
/* EBDA70 801A5DC0 44813000 */  mtc1        $at, $ft1
/* EBDA74 801A5DC4 00000000 */  nop
/* EBDA78 801A5DC8 4606603C */  c.lt.s      $fa0, $ft1
/* EBDA7C 801A5DCC 00000000 */  nop
/* EBDA80 801A5DD0 4502000C */  bc1fl       .Li6_801A5E04
/* EBDA84 801A5DD4 304D0004 */   andi       $t5, $v0, 0x4
.Li6_801A5DD8:
/* EBDA88 801A5DD8 C608000C */  lwc1        $ft2, 0xC($s0)
/* EBDA8C 801A5DDC 8E0B01C4 */  lw          $t3, 0x1C4($s0)
/* EBDA90 801A5DE0 3C02800E */  lui         $v0, %hi(gControllerHold)
/* EBDA94 801A5DE4 460E4281 */  sub.s       $ft3, $ft2, $fa1
/* EBDA98 801A5DE8 000B6080 */  sll         $t4, $t3, 2
/* EBDA9C 801A5DEC 018B6023 */  subu        $t4, $t4, $t3
/* EBDAA0 801A5DF0 000C6040 */  sll         $t4, $t4, 1
/* EBDAA4 801A5DF4 004C1021 */  addu        $v0, $v0, $t4
/* EBDAA8 801A5DF8 E60A000C */  swc1        $ft3, 0xC($s0)
/* EBDAAC 801A5DFC 9442D880 */  lhu         $v0, %lo(gControllerHold)($v0)
/* EBDAB0 801A5E00 304D0004 */  andi        $t5, $v0, 0x4
.Li6_801A5E04:
/* EBDAB4 801A5E04 15A00007 */  bnez        $t5, .Li6_801A5E24
/* EBDAB8 801A5E08 3C014220 */   lui        $at, (0x42200000 >> 16)
/* EBDABC 801A5E0C 44818000 */  mtc1        $at, $ft4
/* EBDAC0 801A5E10 00000000 */  nop
/* EBDAC4 801A5E14 460C803C */  c.lt.s      $ft4, $fa0
/* EBDAC8 801A5E18 00000000 */  nop
/* EBDACC 801A5E1C 45020005 */  bc1fl       .Li6_801A5E34
/* EBDAD0 801A5E20 3C0141F0 */   lui        $at, (0x41F00000 >> 16)
.Li6_801A5E24:
/* EBDAD4 801A5E24 C612000C */  lwc1        $ft5, 0xC($s0)
/* EBDAD8 801A5E28 460E9100 */  add.s       $ft0, $ft5, $fa1
/* EBDADC 801A5E2C E604000C */  swc1        $ft0, 0xC($s0)
/* EBDAE0 801A5E30 3C0141F0 */  lui         $at, (0x41F00000 >> 16)
.Li6_801A5E34:
/* EBDAE4 801A5E34 44811000 */  mtc1        $at, $fv1
/* EBDAE8 801A5E38 C6000008 */  lwc1        $fv0, 0x8($s0)
/* EBDAEC 801A5E3C 3C01C1F0 */  lui         $at, (0xC1F00000 >> 16)
/* EBDAF0 801A5E40 44816000 */  mtc1        $at, $fa0
/* EBDAF4 801A5E44 4600103C */  c.lt.s      $fv1, $fv0
/* EBDAF8 801A5E48 3C0141A0 */  lui         $at, (0x41A00000 >> 16)
/* EBDAFC 801A5E4C 45020004 */  bc1fl       .Li6_801A5E60
/* EBDB00 801A5E50 460C003C */   c.lt.s     $fv0, $fa0
/* EBDB04 801A5E54 E6020008 */  swc1        $fv1, 0x8($s0)
/* EBDB08 801A5E58 C6000008 */  lwc1        $fv0, 0x8($s0)
/* EBDB0C 801A5E5C 460C003C */  c.lt.s      $fv0, $fa0
.Li6_801A5E60:
/* EBDB10 801A5E60 00000000 */  nop
/* EBDB14 801A5E64 45020003 */  bc1fl       .Li6_801A5E74
/* EBDB18 801A5E68 C600000C */   lwc1       $fv0, 0xC($s0)
/* EBDB1C 801A5E6C E60C0008 */  swc1        $fa0, 0x8($s0)
/* EBDB20 801A5E70 C600000C */  lwc1        $fv0, 0xC($s0)
.Li6_801A5E74:
/* EBDB24 801A5E74 4600103C */  c.lt.s      $fv1, $fv0
/* EBDB28 801A5E78 00000000 */  nop
/* EBDB2C 801A5E7C 45020004 */  bc1fl       .Li6_801A5E90
/* EBDB30 801A5E80 460C003C */   c.lt.s     $fv0, $fa0
/* EBDB34 801A5E84 E602000C */  swc1        $fv1, 0xC($s0)
/* EBDB38 801A5E88 C600000C */  lwc1        $fv0, 0xC($s0)
/* EBDB3C 801A5E8C 460C003C */  c.lt.s      $fv0, $fa0
.Li6_801A5E90:
/* EBDB40 801A5E90 44811000 */  mtc1        $at, $fv1
/* EBDB44 801A5E94 3C01C1A0 */  lui         $at, (0xC1A00000 >> 16)
/* EBDB48 801A5E98 340F0001 */  ori         $t7, $zero, 0x1
/* EBDB4C 801A5E9C 45020003 */  bc1fl       .Li6_801A5EAC
/* EBDB50 801A5EA0 C6000008 */   lwc1       $fv0, 0x8($s0)
/* EBDB54 801A5EA4 E60C000C */  swc1        $fa0, 0xC($s0)
/* EBDB58 801A5EA8 C6000008 */  lwc1        $fv0, 0x8($s0)
.Li6_801A5EAC:
/* EBDB5C 801A5EAC 44816000 */  mtc1        $at, $fa0
/* EBDB60 801A5EB0 AE000228 */  sw          $zero, 0x228($s0)
/* EBDB64 801A5EB4 4600103C */  c.lt.s      $fv1, $fv0
/* EBDB68 801A5EB8 00000000 */  nop
/* EBDB6C 801A5EBC 45020004 */  bc1fl       .Li6_801A5ED0
/* EBDB70 801A5EC0 460C003C */   c.lt.s     $fv0, $fa0
/* EBDB74 801A5EC4 AE0F0228 */  sw          $t7, 0x228($s0)
/* EBDB78 801A5EC8 C6000008 */  lwc1        $fv0, 0x8($s0)
/* EBDB7C 801A5ECC 460C003C */  c.lt.s      $fv0, $fa0
.Li6_801A5ED0:
/* EBDB80 801A5ED0 00000000 */  nop
/* EBDB84 801A5ED4 45020005 */  bc1fl       .Li6_801A5EEC
/* EBDB88 801A5ED8 C600000C */   lwc1       $fv0, 0xC($s0)
/* EBDB8C 801A5EDC 8E180228 */  lw          $t8, 0x228($s0)
/* EBDB90 801A5EE0 37190002 */  ori         $t9, $t8, 0x2
/* EBDB94 801A5EE4 AE190228 */  sw          $t9, 0x228($s0)
/* EBDB98 801A5EE8 C600000C */  lwc1        $fv0, 0xC($s0)
.Li6_801A5EEC:
/* EBDB9C 801A5EEC 4600103C */  c.lt.s      $fv1, $fv0
/* EBDBA0 801A5EF0 00000000 */  nop
/* EBDBA4 801A5EF4 45020006 */  bc1fl       .Li6_801A5F10
/* EBDBA8 801A5EF8 460C003C */   c.lt.s     $fv0, $fa0
/* EBDBAC 801A5EFC 8E080228 */  lw          $t0, 0x228($s0)
/* EBDBB0 801A5F00 C600000C */  lwc1        $fv0, 0xC($s0)
/* EBDBB4 801A5F04 35090008 */  ori         $t1, $t0, 0x8
/* EBDBB8 801A5F08 AE090228 */  sw          $t1, 0x228($s0)
/* EBDBBC 801A5F0C 460C003C */  c.lt.s      $fv0, $fa0
.Li6_801A5F10:
/* EBDBC0 801A5F10 00000000 */  nop
/* EBDBC4 801A5F14 45020005 */  bc1fl       .Li6_801A5F2C
/* EBDBC8 801A5F18 8E0C01C4 */   lw         $t4, 0x1C4($s0)
/* EBDBCC 801A5F1C 8E0A0228 */  lw          $t2, 0x228($s0)
/* EBDBD0 801A5F20 354B0004 */  ori         $t3, $t2, 0x4
/* EBDBD4 801A5F24 AE0B0228 */  sw          $t3, 0x228($s0)
/* EBDBD8 801A5F28 8E0C01C4 */  lw          $t4, 0x1C4($s0)
.Li6_801A5F2C:
/* EBDBDC 801A5F2C 3C0E800E */  lui         $t6, %hi(gControllerPress)
/* EBDBE0 801A5F30 01830019 */  multu       $t4, $v1
/* EBDBE4 801A5F34 00006812 */  mflo        $t5
/* EBDBE8 801A5F38 01CD7021 */  addu        $t6, $t6, $t5
/* EBDBEC 801A5F3C 95CED898 */  lhu         $t6, %lo(gControllerPress)($t6)
/* EBDBF0 801A5F40 31CF4000 */  andi        $t7, $t6, 0x4000
/* EBDBF4 801A5F44 51E00006 */  beql        $t7, $zero, .Li6_801A5F60
/* EBDBF8 801A5F48 C6060008 */   lwc1       $ft1, 0x8($s0)
/* EBDBFC 801A5F4C 44800000 */  mtc1        $zero, $fv0
/* EBDC00 801A5F50 00000000 */  nop
/* EBDC04 801A5F54 E600000C */  swc1        $fv0, 0xC($s0)
/* EBDC08 801A5F58 E6000008 */  swc1        $fv0, 0x8($s0)
/* EBDC0C 801A5F5C C6060008 */  lwc1        $ft1, 0x8($s0)
.Li6_801A5F60:
/* EBDC10 801A5F60 3C01801A */  lui         $at, %hi(D_i6_801A7EE4)
/* EBDC14 801A5F64 C42A7EE4 */  lwc1        $ft3, %lo(D_i6_801A7EE4)($at)
/* EBDC18 801A5F68 46003207 */  neg.s       $ft2, $ft1
/* EBDC1C 801A5F6C 3C074040 */  lui         $a3, (0x40400000 >> 16)
/* EBDC20 801A5F70 44054000 */  mfc1        $a1, $ft2
/* EBDC24 801A5F74 0C026F0B */  jal         Math_SmoothStepToF
/* EBDC28 801A5F78 E7AA0010 */   swc1       $ft3, 0x10($sp)
/* EBDC2C 801A5F7C C610000C */  lwc1        $ft4, 0xC($s0)
/* EBDC30 801A5F80 3C01801A */  lui         $at, %hi(D_i6_801A7EE8)
/* EBDC34 801A5F84 C4247EE8 */  lwc1        $ft0, %lo(D_i6_801A7EE8)($at)
/* EBDC38 801A5F88 46008487 */  neg.s       $ft5, $ft4
/* EBDC3C 801A5F8C 2604017C */  addiu       $a0, $s0, 0x17C
/* EBDC40 801A5F90 44059000 */  mfc1        $a1, $ft5
/* EBDC44 801A5F94 3C063F00 */  lui         $a2, (0x3F000000 >> 16)
/* EBDC48 801A5F98 3C074040 */  lui         $a3, (0x40400000 >> 16)
/* EBDC4C 801A5F9C 0C026F0B */  jal         Math_SmoothStepToF
/* EBDC50 801A5FA0 E7A40010 */   swc1       $ft0, 0x10($sp)
/* EBDC54 801A5FA4 0C06962A */  jal         func_i6_801A58A8
/* EBDC58 801A5FA8 02002025 */   or         $a0, $s0, $zero
/* EBDC5C 801A5FAC 8FBF0024 */  lw          $ra, 0x24($sp)
/* EBDC60 801A5FB0 8FB00020 */  lw          $s0, 0x20($sp)
/* EBDC64 801A5FB4 27BD0030 */  addiu       $sp, $sp, 0x30
/* EBDC68 801A5FB8 03E00008 */  jr          $ra
/* EBDC6C 801A5FBC 00000000 */   nop
.section .late_rodata
dlabel D_i6_801A7EEC
/* EBFB9C 801A7EEC 3C8EFA35 */ .float 0.01745329238

dlabel D_i6_801A7EF0
/* EBFBA0 801A7EF0 3E99999A */ .float 0.3000000119

dlabel D_i6_801A7EF4
/* EBFBA4 801A7EF4 3E99999A */ .float 0.3000000119


.section .text
/* Generated by spimdisasm 1.19.1.dev0 */

glabel func_i6_801A5FC0
/* EBDC70 801A5FC0 27BDFFB8 */  addiu       $sp, $sp, -0x48
/* EBDC74 801A5FC4 AFB10020 */  sw          $s1, 0x20($sp)
/* EBDC78 801A5FC8 3C118014 */  lui         $s1, %hi(gCalcMatrix)
/* EBDC7C 801A5FCC AFB0001C */  sw          $s0, 0x1C($sp)
/* EBDC80 801A5FD0 F7B40010 */  sdc1        $fs0, 0x10($sp)
/* EBDC84 801A5FD4 3C01801A */  lui         $at, %hi(D_i6_801A7EEC)
/* EBDC88 801A5FD8 44800000 */  mtc1        $zero, $fv0
/* EBDC8C 801A5FDC C4347EEC */  lwc1        $fs0, %lo(D_i6_801A7EEC)($at)
/* EBDC90 801A5FE0 00808025 */  or          $s0, $a0, $zero
/* EBDC94 801A5FE4 2631BBC8 */  addiu       $s1, $s1, %lo(gCalcMatrix)
/* EBDC98 801A5FE8 AFBF0024 */  sw          $ra, 0x24($sp)
/* EBDC9C 801A5FEC 3C0142C8 */  lui         $at, (0x42C80000 >> 16)
/* EBDCA0 801A5FF0 44812000 */  mtc1        $at, $ft0
/* EBDCA4 801A5FF4 E7A0003C */  swc1        $fv0, 0x3C($sp)
/* EBDCA8 801A5FF8 E7A00040 */  swc1        $fv0, 0x40($sp)
/* EBDCAC 801A5FFC 3C01801A */  lui         $at, %hi(D_i6_801A7EF0)
/* EBDCB0 801A6000 E7A40044 */  swc1        $ft0, 0x44($sp)
/* EBDCB4 801A6004 C6060134 */  lwc1        $ft1, 0x134($s0)
/* EBDCB8 801A6008 C4287EF0 */  lwc1        $ft2, %lo(D_i6_801A7EF0)($at)
/* EBDCBC 801A600C C6100000 */  lwc1        $ft4, 0x0($s0)
/* EBDCC0 801A6010 8E240000 */  lw          $a0, 0x0($s1)
/* EBDCC4 801A6014 46083282 */  mul.s       $ft3, $ft1, $ft2
/* EBDCC8 801A6018 00003025 */  or          $a2, $zero, $zero
/* EBDCCC 801A601C 460A8480 */  add.s       $ft5, $ft4, $ft3
/* EBDCD0 801A6020 46149102 */  mul.s       $ft0, $ft5, $fs0
/* EBDCD4 801A6024 44052000 */  mfc1        $a1, $ft0
/* EBDCD8 801A6028 0C0017A4 */  jal         Matrix_RotateY
/* EBDCDC 801A602C 00000000 */   nop
/* EBDCE0 801A6030 3C01801A */  lui         $at, %hi(D_i6_801A7EF4)
/* EBDCE4 801A6034 C4287EF4 */  lwc1        $ft2, %lo(D_i6_801A7EF4)($at)
/* EBDCE8 801A6038 C6060134 */  lwc1        $ft1, 0x134($s0)
/* EBDCEC 801A603C C60A0004 */  lwc1        $ft3, 0x4($s0)
/* EBDCF0 801A6040 8E240000 */  lw          $a0, 0x0($s1)
/* EBDCF4 801A6044 46083402 */  mul.s       $ft4, $ft1, $ft2
/* EBDCF8 801A6048 24060001 */  addiu       $a2, $zero, 0x1
/* EBDCFC 801A604C 46105480 */  add.s       $ft5, $ft3, $ft4
/* EBDD00 801A6050 46149102 */  mul.s       $ft0, $ft5, $fs0
/* EBDD04 801A6054 44052000 */  mfc1        $a1, $ft0
/* EBDD08 801A6058 0C001751 */  jal         Matrix_RotateX
/* EBDD0C 801A605C 00000000 */   nop
/* EBDD10 801A6060 C60600EC */  lwc1        $ft1, 0xEC($s0)
/* EBDD14 801A6064 8E240000 */  lw          $a0, 0x0($s1)
/* EBDD18 801A6068 24060001 */  addiu       $a2, $zero, 0x1
/* EBDD1C 801A606C 46143202 */  mul.s       $ft2, $ft1, $fs0
/* EBDD20 801A6070 44054000 */  mfc1        $a1, $ft2
/* EBDD24 801A6074 0C0017F8 */  jal         Matrix_RotateZ
/* EBDD28 801A6078 00000000 */   nop
/* EBDD2C 801A607C C60A0180 */  lwc1        $ft3, 0x180($s0)
/* EBDD30 801A6080 8E240000 */  lw          $a0, 0x0($s1)
/* EBDD34 801A6084 24060001 */  addiu       $a2, $zero, 0x1
/* EBDD38 801A6088 46145402 */  mul.s       $ft4, $ft3, $fs0
/* EBDD3C 801A608C 44058000 */  mfc1        $a1, $ft4
/* EBDD40 801A6090 0C0017A4 */  jal         Matrix_RotateY
/* EBDD44 801A6094 00000000 */   nop
/* EBDD48 801A6098 C612017C */  lwc1        $ft5, 0x17C($s0)
/* EBDD4C 801A609C 8E240000 */  lw          $a0, 0x0($s1)
/* EBDD50 801A60A0 24060001 */  addiu       $a2, $zero, 0x1
/* EBDD54 801A60A4 46149102 */  mul.s       $ft0, $ft5, $fs0
/* EBDD58 801A60A8 44052000 */  mfc1        $a1, $ft0
/* EBDD5C 801A60AC 0C001751 */  jal         Matrix_RotateX
/* EBDD60 801A60B0 00000000 */   nop
/* EBDD64 801A60B4 44803000 */  mtc1        $zero, $ft1
/* EBDD68 801A60B8 8E240000 */  lw          $a0, 0x0($s1)
/* EBDD6C 801A60BC 24060001 */  addiu       $a2, $zero, 0x1
/* EBDD70 801A60C0 46143002 */  mul.s       $fv0, $ft1, $fs0
/* EBDD74 801A60C4 44050000 */  mfc1        $a1, $fv0
/* EBDD78 801A60C8 0C0017A4 */  jal         Matrix_RotateY
/* EBDD7C 801A60CC E7A0002C */   swc1       $fv0, 0x2C($sp)
/* EBDD80 801A60D0 C7A0002C */  lwc1        $fv0, 0x2C($sp)
/* EBDD84 801A60D4 8E240000 */  lw          $a0, 0x0($s1)
/* EBDD88 801A60D8 24060001 */  addiu       $a2, $zero, 0x1
/* EBDD8C 801A60DC 44050000 */  mfc1        $a1, $fv0
/* EBDD90 801A60E0 0C001751 */  jal         Matrix_RotateX
/* EBDD94 801A60E4 00000000 */   nop
/* EBDD98 801A60E8 8E240000 */  lw          $a0, 0x0($s1)
/* EBDD9C 801A60EC 27A5003C */  addiu       $a1, $sp, 0x3C
/* EBDDA0 801A60F0 0C001A5C */  jal         Matrix_MultVec3f
/* EBDDA4 801A60F4 27A60030 */   addiu      $a2, $sp, 0x30
/* EBDDA8 801A60F8 C6000074 */  lwc1        $fv0, 0x74($s0)
/* EBDDAC 801A60FC C7A80030 */  lwc1        $ft2, 0x30($sp)
/* EBDDB0 801A6100 C6020078 */  lwc1        $fv1, 0x78($s0)
/* EBDDB4 801A6104 3C028017 */  lui         $v0, %hi(D_80177D20)
/* EBDDB8 801A6108 46080280 */  add.s       $ft3, $fv0, $ft2
/* EBDDBC 801A610C 24427D20 */  addiu       $v0, $v0, %lo(D_80177D20)
/* EBDDC0 801A6110 C60C007C */  lwc1        $fa0, 0x7C($s0)
/* EBDDC4 801A6114 E60A004C */  swc1        $ft3, 0x4C($s0)
/* EBDDC8 801A6118 C7B00034 */  lwc1        $ft4, 0x34($sp)
/* EBDDCC 801A611C 46101480 */  add.s       $ft5, $fv1, $ft4
/* EBDDD0 801A6120 E6120050 */  swc1        $ft5, 0x50($s0)
/* EBDDD4 801A6124 C4440000 */  lwc1        $ft0, 0x0($v0)
/* EBDDD8 801A6128 C7A80038 */  lwc1        $ft2, 0x38($sp)
/* EBDDDC 801A612C E6000040 */  swc1        $fv0, 0x40($s0)
/* EBDDE0 801A6130 46046180 */  add.s       $ft1, $fa0, $ft0
/* EBDDE4 801A6134 E6020044 */  swc1        $fv1, 0x44($s0)
/* EBDDE8 801A6138 46083280 */  add.s       $ft3, $ft1, $ft2
/* EBDDEC 801A613C E60A0054 */  swc1        $ft3, 0x54($s0)
/* EBDDF0 801A6140 C4500000 */  lwc1        $ft4, 0x0($v0)
/* EBDDF4 801A6144 46106480 */  add.s       $ft5, $fa0, $ft4
/* EBDDF8 801A6148 E6120048 */  swc1        $ft5, 0x48($s0)
/* EBDDFC 801A614C 8FBF0024 */  lw          $ra, 0x24($sp)
/* EBDE00 801A6150 D7B40010 */  ldc1        $fs0, 0x10($sp)
/* EBDE04 801A6154 8FB0001C */  lw          $s0, 0x1C($sp)
/* EBDE08 801A6158 8FB10020 */  lw          $s1, 0x20($sp)
/* EBDE0C 801A615C 03E00008 */  jr          $ra
/* EBDE10 801A6160 27BD0048 */   addiu      $sp, $sp, 0x48
.section .late_rodata
dlabel D_i6_801A7EF8
/* EBFBA8 801A7EF8 3C8EFA35 */ .float 0.01745329238

dlabel D_i6_801A7EFC
/* EBFBAC 801A7EFC 3C8EFA35 */ .float 0.01745329238

dlabel D_i6_801A7F00
/* EBFBB0 801A7F00 C59C4000 */ .float -5000

dlabel D_i6_801A7F04
/* EBFBB4 801A7F04 3C8EFA35 */ .float 0.01745329238

dlabel D_i6_801A7F08
/* EBFBB8 801A7F08 3C8EFA35 */ .float 0.01745329238

dlabel D_i6_801A7F0C
/* EBFBBC 801A7F0C 3C8EFA35 */ .float 0.01745329238

dlabel D_i6_801A7F10
/* EBFBC0 801A7F10 3C8EFA35 */ .float 0.01745329238

dlabel D_i6_801A7F14
/* EBFBC4 801A7F14 3C8EFA35 */ .float 0.01745329238

dlabel D_i6_801A7F18
/* EBFBC8 801A7F18 3C8EFA35 */ .float 0.01745329238

dlabel D_i6_801A7F1C
/* EBFBCC 801A7F1C 3C8EFA35 */ .float 0.01745329238

dlabel D_i6_801A7F20
/* EBFBD0 801A7F20 3C8EFA35 */ .float 0.01745329238
/* EBFBD4 801A7F24 00000000 */ .float 0
/* EBFBD8 801A7F28 00000000 */ .float 0
/* EBFBDC 801A7F2C 00000000 */ .float 0


.section .text
/* Generated by spimdisasm 1.19.1.dev0 */

glabel func_i6_801A6164
/* EBDE14 801A6164 27BDFFD8 */  addiu       $sp, $sp, -0x28
/* EBDE18 801A6168 AFB10020 */  sw          $s1, 0x20($sp)
/* EBDE1C 801A616C 00808825 */  or          $s1, $a0, $zero
/* EBDE20 801A6170 AFBF0024 */  sw          $ra, 0x24($sp)
/* EBDE24 801A6174 AFB0001C */  sw          $s0, 0x1C($sp)
/* EBDE28 801A6178 8E2E01C4 */  lw          $t6, 0x1C4($s1)
/* EBDE2C 801A617C 3C02800E */  lui         $v0, %hi(gControllerHold)
/* EBDE30 801A6180 3C108014 */  lui         $s0, %hi(gGfxMatrix)
/* EBDE34 801A6184 000E7880 */  sll         $t7, $t6, 2
/* EBDE38 801A6188 01EE7823 */  subu        $t7, $t7, $t6
/* EBDE3C 801A618C 000F7840 */  sll         $t7, $t7, 1
/* EBDE40 801A6190 004F1021 */  addu        $v0, $v0, $t7
/* EBDE44 801A6194 9442D880 */  lhu         $v0, %lo(gControllerHold)($v0)
/* EBDE48 801A6198 2610B3C0 */  addiu       $s0, $s0, %lo(gGfxMatrix)
/* EBDE4C 801A619C 30580800 */  andi        $t8, $v0, 0x800
/* EBDE50 801A61A0 13000008 */  beqz        $t8, .Li6_801A61C4
/* EBDE54 801A61A4 30590400 */   andi       $t9, $v0, 0x400
/* EBDE58 801A61A8 3C01801A */  lui         $at, %hi(D_i6_801A6B80)
/* EBDE5C 801A61AC C4246B80 */  lwc1        $ft0, %lo(D_i6_801A6B80)($at)
/* EBDE60 801A61B0 3C014120 */  lui         $at, (0x41200000 >> 16)
/* EBDE64 801A61B4 44813000 */  mtc1        $at, $ft1
/* EBDE68 801A61B8 3C01801A */  lui         $at, %hi(D_i6_801A6B80)
/* EBDE6C 801A61BC 46062200 */  add.s       $ft2, $ft0, $ft1
/* EBDE70 801A61C0 E4286B80 */  swc1        $ft2, %lo(D_i6_801A6B80)($at)
.Li6_801A61C4:
/* EBDE74 801A61C4 13200007 */  beqz        $t9, .Li6_801A61E4
/* EBDE78 801A61C8 3C01801A */   lui        $at, %hi(D_i6_801A6B80)
/* EBDE7C 801A61CC C42A6B80 */  lwc1        $ft3, %lo(D_i6_801A6B80)($at)
/* EBDE80 801A61D0 3C014120 */  lui         $at, (0x41200000 >> 16)
/* EBDE84 801A61D4 44818000 */  mtc1        $at, $ft4
/* EBDE88 801A61D8 3C01801A */  lui         $at, %hi(D_i6_801A6B80)
/* EBDE8C 801A61DC 46105481 */  sub.s       $ft5, $ft3, $ft4
/* EBDE90 801A61E0 E4326B80 */  swc1        $ft5, %lo(D_i6_801A6B80)($at)
.Li6_801A61E4:
/* EBDE94 801A61E4 0C0015C2 */  jal         Matrix_Push
/* EBDE98 801A61E8 02002025 */   or         $a0, $s0, $zero
/* EBDE9C 801A61EC 0C02E4D6 */  jal         RCP_SetupDL_36
/* EBDEA0 801A61F0 00000000 */   nop
/* EBDEA4 801A61F4 44800000 */  mtc1        $zero, $fv0
/* EBDEA8 801A61F8 24080001 */  addiu       $t0, $zero, 0x1
/* EBDEAC 801A61FC AFA80010 */  sw          $t0, 0x10($sp)
/* EBDEB0 801A6200 44050000 */  mfc1        $a1, $fv0
/* EBDEB4 801A6204 44070000 */  mfc1        $a3, $fv0
/* EBDEB8 801A6208 8E040000 */  lw          $a0, 0x0($s0)
/* EBDEBC 801A620C 0C0016C0 */  jal         Matrix_Translate
/* EBDEC0 801A6210 3C06C2C8 */   lui        $a2, (0xC2C80000 >> 16)
/* EBDEC4 801A6214 3C01801A */  lui         $at, %hi(D_i6_801A7EF8)
/* EBDEC8 801A6218 C4267EF8 */  lwc1        $ft1, %lo(D_i6_801A7EF8)($at)
/* EBDECC 801A621C C62400E8 */  lwc1        $ft0, 0xE8($s1)
/* EBDED0 801A6220 8E040000 */  lw          $a0, 0x0($s0)
/* EBDED4 801A6224 24060001 */  addiu       $a2, $zero, 0x1
/* EBDED8 801A6228 46062202 */  mul.s       $ft2, $ft0, $ft1
/* EBDEDC 801A622C 44054000 */  mfc1        $a1, $ft2
/* EBDEE0 801A6230 0C0017A4 */  jal         Matrix_RotateY
/* EBDEE4 801A6234 00000000 */   nop
/* EBDEE8 801A6238 C62A00E4 */  lwc1        $ft3, 0xE4($s1)
/* EBDEEC 801A623C 3C01801A */  lui         $at, %hi(D_i6_801A7EFC)
/* EBDEF0 801A6240 C4327EFC */  lwc1        $ft5, %lo(D_i6_801A7EFC)($at)
/* EBDEF4 801A6244 46005407 */  neg.s       $ft4, $ft3
/* EBDEF8 801A6248 8E040000 */  lw          $a0, 0x0($s0)
/* EBDEFC 801A624C 46128102 */  mul.s       $ft0, $ft4, $ft5
/* EBDF00 801A6250 24060001 */  addiu       $a2, $zero, 0x1
/* EBDF04 801A6254 44052000 */  mfc1        $a1, $ft0
/* EBDF08 801A6258 0C001751 */  jal         Matrix_RotateX
/* EBDF0C 801A625C 00000000 */   nop
/* EBDF10 801A6260 8E2901B0 */  lw          $t1, 0x1B0($s1)
/* EBDF14 801A6264 29210002 */  slti        $at, $t1, 0x2
/* EBDF18 801A6268 50200017 */  beql        $at, $zero, .Li6_801A62C8
/* EBDF1C 801A626C 3C07C59C */   lui        $a3, (0xC59C4000 >> 16)
/* EBDF20 801A6270 8E2A01BC */  lw          $t2, 0x1BC($s1)
/* EBDF24 801A6274 3C01801A */  lui         $at, %hi(D_i6_801A7F00)
/* EBDF28 801A6278 C42A7F00 */  lwc1        $ft3, %lo(D_i6_801A7F00)($at)
/* EBDF2C 801A627C 000A5880 */  sll         $t3, $t2, 2
/* EBDF30 801A6280 016A5823 */  subu        $t3, $t3, $t2
/* EBDF34 801A6284 000B58C0 */  sll         $t3, $t3, 3
/* EBDF38 801A6288 016A5821 */  addu        $t3, $t3, $t2
/* EBDF3C 801A628C 448B3000 */  mtc1        $t3, $ft1
/* EBDF40 801A6290 44800000 */  mtc1        $zero, $fv0
/* EBDF44 801A6294 240C0001 */  addiu       $t4, $zero, 0x1
/* EBDF48 801A6298 46803220 */  cvt.s.w     $ft2, $ft1
/* EBDF4C 801A629C 44050000 */  mfc1        $a1, $fv0
/* EBDF50 801A62A0 44060000 */  mfc1        $a2, $fv0
/* EBDF54 801A62A4 AFAC0010 */  sw          $t4, 0x10($sp)
/* EBDF58 801A62A8 8E040000 */  lw          $a0, 0x0($s0)
/* EBDF5C 801A62AC 460A4400 */  add.s       $ft4, $ft2, $ft3
/* EBDF60 801A62B0 44078000 */  mfc1        $a3, $ft4
/* EBDF64 801A62B4 0C0016C0 */  jal         Matrix_Translate
/* EBDF68 801A62B8 00000000 */   nop
/* EBDF6C 801A62BC 1000000A */  b           .Li6_801A62E8
/* EBDF70 801A62C0 3C014140 */   lui        $at, (0x41400000 >> 16)
/* EBDF74 801A62C4 3C07C59C */  lui         $a3, (0xC59C4000 >> 16)
.Li6_801A62C8:
/* EBDF78 801A62C8 240D0001 */  addiu       $t5, $zero, 0x1
/* EBDF7C 801A62CC AFAD0010 */  sw          $t5, 0x10($sp)
/* EBDF80 801A62D0 34E74000 */  ori         $a3, $a3, (0xC59C4000 & 0xFFFF)
/* EBDF84 801A62D4 8E040000 */  lw          $a0, 0x0($s0)
/* EBDF88 801A62D8 24050000 */  addiu       $a1, $zero, 0x0
/* EBDF8C 801A62DC 0C0016C0 */  jal         Matrix_Translate
/* EBDF90 801A62E0 24060000 */   addiu      $a2, $zero, 0x0
/* EBDF94 801A62E4 3C014140 */  lui         $at, (0x41400000 >> 16)
.Li6_801A62E8:
/* EBDF98 801A62E8 44810000 */  mtc1        $at, $fv0
/* EBDF9C 801A62EC 240E0001 */  addiu       $t6, $zero, 0x1
/* EBDFA0 801A62F0 AFAE0010 */  sw          $t6, 0x10($sp)
/* EBDFA4 801A62F4 44050000 */  mfc1        $a1, $fv0
/* EBDFA8 801A62F8 44060000 */  mfc1        $a2, $fv0
/* EBDFAC 801A62FC 8E040000 */  lw          $a0, 0x0($s0)
/* EBDFB0 801A6300 0C00170D */  jal         Matrix_Scale
/* EBDFB4 801A6304 3C073F80 */   lui        $a3, (0x3F800000 >> 16)
/* EBDFB8 801A6308 3C048013 */  lui         $a0, %hi(gMasterDisp)
/* EBDFBC 801A630C 0C001BAE */  jal         Matrix_SetGfxMtx
/* EBDFC0 801A6310 24847E64 */   addiu      $a0, $a0, %lo(gMasterDisp)
/* EBDFC4 801A6314 0C0015D0 */  jal         Matrix_Pop
/* EBDFC8 801A6318 02002025 */   or         $a0, $s0, $zero
/* EBDFCC 801A631C 0C02E900 */  jal         RCP_SetupDL_27
/* EBDFD0 801A6320 00000000 */   nop
/* EBDFD4 801A6324 8E2F01BC */  lw          $t7, 0x1BC($s1)
/* EBDFD8 801A6328 29E10015 */  slti        $at, $t7, 0x15
/* EBDFDC 801A632C 14200010 */  bnez        $at, .Li6_801A6370
/* EBDFE0 801A6330 00000000 */   nop
/* EBDFE4 801A6334 8E3801B0 */  lw          $t8, 0x1B0($s1)
/* EBDFE8 801A6338 3C028013 */  lui         $v0, %hi(gMasterDisp)
/* EBDFEC 801A633C 3C08FA00 */  lui         $t0, (0xFA000000 >> 16)
/* EBDFF0 801A6340 2B010002 */  slti        $at, $t8, 0x2
/* EBDFF4 801A6344 1420000A */  bnez        $at, .Li6_801A6370
/* EBDFF8 801A6348 3C09C800 */   lui        $t1, (0xC80064FF >> 16)
/* EBDFFC 801A634C 8C427E64 */  lw          $v0, %lo(gMasterDisp)($v0)
/* EBE000 801A6350 3C018013 */  lui         $at, %hi(gMasterDisp)
/* EBE004 801A6354 352964FF */  ori         $t1, $t1, (0xC80064FF & 0xFFFF)
/* EBE008 801A6358 24590008 */  addiu       $t9, $v0, 0x8
/* EBE00C 801A635C AC397E64 */  sw          $t9, %lo(gMasterDisp)($at)
/* EBE010 801A6360 AC490004 */  sw          $t1, 0x4($v0)
/* EBE014 801A6364 AC480000 */  sw          $t0, 0x0($v0)
/* EBE018 801A6368 1000000A */  b           .Li6_801A6394
/* EBE01C 801A636C 00000000 */   nop
.Li6_801A6370:
/* EBE020 801A6370 3C028013 */  lui         $v0, %hi(gMasterDisp)
/* EBE024 801A6374 8C427E64 */  lw          $v0, %lo(gMasterDisp)($v0)
/* EBE028 801A6378 3C018013 */  lui         $at, %hi(gMasterDisp)
/* EBE02C 801A637C 3C0BFA00 */  lui         $t3, (0xFA000000 >> 16)
/* EBE030 801A6380 244A0008 */  addiu       $t2, $v0, 0x8
/* EBE034 801A6384 AC2A7E64 */  sw          $t2, %lo(gMasterDisp)($at)
/* EBE038 801A6388 240CFFFF */  addiu       $t4, $zero, -0x1
/* EBE03C 801A638C AC4C0004 */  sw          $t4, 0x4($v0)
/* EBE040 801A6390 AC4B0000 */  sw          $t3, 0x0($v0)
.Li6_801A6394:
/* EBE044 801A6394 0C0015C2 */  jal         Matrix_Push
/* EBE048 801A6398 02002025 */   or         $a0, $s0, $zero
/* EBE04C 801A639C 8E2D01BC */  lw          $t5, 0x1BC($s1)
/* EBE050 801A63A0 3C01C2C8 */  lui         $at, (0xC2C80000 >> 16)
/* EBE054 801A63A4 44810000 */  mtc1        $at, $fv0
/* EBE058 801A63A8 448D9000 */  mtc1        $t5, $ft5
/* EBE05C 801A63AC 3C01C348 */  lui         $at, (0xC3480000 >> 16)
/* EBE060 801A63B0 44813000 */  mtc1        $at, $ft1
/* EBE064 801A63B4 46809120 */  cvt.s.w     $ft0, $ft5
/* EBE068 801A63B8 240E0001 */  addiu       $t6, $zero, 0x1
/* EBE06C 801A63BC 44050000 */  mfc1        $a1, $fv0
/* EBE070 801A63C0 44060000 */  mfc1        $a2, $fv0
/* EBE074 801A63C4 AFAE0010 */  sw          $t6, 0x10($sp)
/* EBE078 801A63C8 8E040000 */  lw          $a0, 0x0($s0)
/* EBE07C 801A63CC 46062200 */  add.s       $ft2, $ft0, $ft1
/* EBE080 801A63D0 44074000 */  mfc1        $a3, $ft2
/* EBE084 801A63D4 0C0016C0 */  jal         Matrix_Translate
/* EBE088 801A63D8 00000000 */   nop
/* EBE08C 801A63DC 3C01801A */  lui         $at, %hi(D_i6_801A7F04)
/* EBE090 801A63E0 C4307F04 */  lwc1        $ft4, %lo(D_i6_801A7F04)($at)
/* EBE094 801A63E4 C62A00E8 */  lwc1        $ft3, 0xE8($s1)
/* EBE098 801A63E8 8E040000 */  lw          $a0, 0x0($s0)
/* EBE09C 801A63EC 24060001 */  addiu       $a2, $zero, 0x1
/* EBE0A0 801A63F0 46105482 */  mul.s       $ft5, $ft3, $ft4
/* EBE0A4 801A63F4 44059000 */  mfc1        $a1, $ft5
/* EBE0A8 801A63F8 0C0017A4 */  jal         Matrix_RotateY
/* EBE0AC 801A63FC 00000000 */   nop
/* EBE0B0 801A6400 C62400E4 */  lwc1        $ft0, 0xE4($s1)
/* EBE0B4 801A6404 3C01801A */  lui         $at, %hi(D_i6_801A7F08)
/* EBE0B8 801A6408 C4287F08 */  lwc1        $ft2, %lo(D_i6_801A7F08)($at)
/* EBE0BC 801A640C 46002187 */  neg.s       $ft1, $ft0
/* EBE0C0 801A6410 8E040000 */  lw          $a0, 0x0($s0)
/* EBE0C4 801A6414 46083282 */  mul.s       $ft3, $ft1, $ft2
/* EBE0C8 801A6418 24060001 */  addiu       $a2, $zero, 0x1
/* EBE0CC 801A641C 44055000 */  mfc1        $a1, $ft3
/* EBE0D0 801A6420 0C001751 */  jal         Matrix_RotateX
/* EBE0D4 801A6424 00000000 */   nop
/* EBE0D8 801A6428 3C013F80 */  lui         $at, (0x3F800000 >> 16)
/* EBE0DC 801A642C 44810000 */  mtc1        $at, $fv0
/* EBE0E0 801A6430 240F0001 */  addiu       $t7, $zero, 0x1
/* EBE0E4 801A6434 AFAF0010 */  sw          $t7, 0x10($sp)
/* EBE0E8 801A6438 44050000 */  mfc1        $a1, $fv0
/* EBE0EC 801A643C 44060000 */  mfc1        $a2, $fv0
/* EBE0F0 801A6440 44070000 */  mfc1        $a3, $fv0
/* EBE0F4 801A6444 0C00170D */  jal         Matrix_Scale
/* EBE0F8 801A6448 8E040000 */   lw         $a0, 0x0($s0)
/* EBE0FC 801A644C 3C048013 */  lui         $a0, %hi(gMasterDisp)
/* EBE100 801A6450 0C001BAE */  jal         Matrix_SetGfxMtx
/* EBE104 801A6454 24847E64 */   addiu      $a0, $a0, %lo(gMasterDisp)
/* EBE108 801A6458 0C0015D0 */  jal         Matrix_Pop
/* EBE10C 801A645C 02002025 */   or         $a0, $s0, $zero
/* EBE110 801A6460 0C0015C2 */  jal         Matrix_Push
/* EBE114 801A6464 02002025 */   or         $a0, $s0, $zero
/* EBE118 801A6468 8E3801BC */  lw          $t8, 0x1BC($s1)
/* EBE11C 801A646C 3C01C348 */  lui         $at, (0xC3480000 >> 16)
/* EBE120 801A6470 44812000 */  mtc1        $at, $ft0
/* EBE124 801A6474 44988000 */  mtc1        $t8, $ft4
/* EBE128 801A6478 24190001 */  addiu       $t9, $zero, 0x1
/* EBE12C 801A647C AFB90010 */  sw          $t9, 0x10($sp)
/* EBE130 801A6480 468084A0 */  cvt.s.w     $ft5, $ft4
/* EBE134 801A6484 8E040000 */  lw          $a0, 0x0($s0)
/* EBE138 801A6488 3C0542C8 */  lui         $a1, (0x42C80000 >> 16)
/* EBE13C 801A648C 3C06C2C8 */  lui         $a2, (0xC2C80000 >> 16)
/* EBE140 801A6490 46049180 */  add.s       $ft1, $ft5, $ft0
/* EBE144 801A6494 44073000 */  mfc1        $a3, $ft1
/* EBE148 801A6498 0C0016C0 */  jal         Matrix_Translate
/* EBE14C 801A649C 00000000 */   nop
/* EBE150 801A64A0 3C01801A */  lui         $at, %hi(D_i6_801A7F0C)
/* EBE154 801A64A4 C42A7F0C */  lwc1        $ft3, %lo(D_i6_801A7F0C)($at)
/* EBE158 801A64A8 C62800E8 */  lwc1        $ft2, 0xE8($s1)
/* EBE15C 801A64AC 8E040000 */  lw          $a0, 0x0($s0)
/* EBE160 801A64B0 24060001 */  addiu       $a2, $zero, 0x1
/* EBE164 801A64B4 460A4402 */  mul.s       $ft4, $ft2, $ft3
/* EBE168 801A64B8 44058000 */  mfc1        $a1, $ft4
/* EBE16C 801A64BC 0C0017A4 */  jal         Matrix_RotateY
/* EBE170 801A64C0 00000000 */   nop
/* EBE174 801A64C4 C63200E4 */  lwc1        $ft5, 0xE4($s1)
/* EBE178 801A64C8 3C01801A */  lui         $at, %hi(D_i6_801A7F10)
/* EBE17C 801A64CC C4267F10 */  lwc1        $ft1, %lo(D_i6_801A7F10)($at)
/* EBE180 801A64D0 46009107 */  neg.s       $ft0, $ft5
/* EBE184 801A64D4 8E040000 */  lw          $a0, 0x0($s0)
/* EBE188 801A64D8 46062202 */  mul.s       $ft2, $ft0, $ft1
/* EBE18C 801A64DC 24060001 */  addiu       $a2, $zero, 0x1
/* EBE190 801A64E0 44054000 */  mfc1        $a1, $ft2
/* EBE194 801A64E4 0C001751 */  jal         Matrix_RotateX
/* EBE198 801A64E8 00000000 */   nop
/* EBE19C 801A64EC 3C013F80 */  lui         $at, (0x3F800000 >> 16)
/* EBE1A0 801A64F0 44810000 */  mtc1        $at, $fv0
/* EBE1A4 801A64F4 24080001 */  addiu       $t0, $zero, 0x1
/* EBE1A8 801A64F8 AFA80010 */  sw          $t0, 0x10($sp)
/* EBE1AC 801A64FC 44050000 */  mfc1        $a1, $fv0
/* EBE1B0 801A6500 44060000 */  mfc1        $a2, $fv0
/* EBE1B4 801A6504 44070000 */  mfc1        $a3, $fv0
/* EBE1B8 801A6508 0C00170D */  jal         Matrix_Scale
/* EBE1BC 801A650C 8E040000 */   lw         $a0, 0x0($s0)
/* EBE1C0 801A6510 3C048013 */  lui         $a0, %hi(gMasterDisp)
/* EBE1C4 801A6514 0C001BAE */  jal         Matrix_SetGfxMtx
/* EBE1C8 801A6518 24847E64 */   addiu      $a0, $a0, %lo(gMasterDisp)
/* EBE1CC 801A651C 0C0015D0 */  jal         Matrix_Pop
/* EBE1D0 801A6520 02002025 */   or         $a0, $s0, $zero
/* EBE1D4 801A6524 8E2901BC */  lw          $t1, 0x1BC($s1)
/* EBE1D8 801A6528 29210015 */  slti        $at, $t1, 0x15
/* EBE1DC 801A652C 54200083 */  bnel        $at, $zero, .Li6_801A673C
/* EBE1E0 801A6530 8FBF0024 */   lw         $ra, 0x24($sp)
/* EBE1E4 801A6534 8E2A01B0 */  lw          $t2, 0x1B0($s1)
/* EBE1E8 801A6538 29410002 */  slti        $at, $t2, 0x2
/* EBE1EC 801A653C 5420007F */  bnel        $at, $zero, .Li6_801A673C
/* EBE1F0 801A6540 8FBF0024 */   lw         $ra, 0x24($sp)
/* EBE1F4 801A6544 0C02E850 */  jal         RCP_SetupDL_64
/* EBE1F8 801A6548 00000000 */   nop
/* EBE1FC 801A654C 3C058013 */  lui         $a1, %hi(gMasterDisp)
/* EBE200 801A6550 24A57E64 */  addiu       $a1, $a1, %lo(gMasterDisp)
/* EBE204 801A6554 8CA20000 */  lw          $v0, 0x0($a1)
/* EBE208 801A6558 3C0CFA00 */  lui         $t4, (0xFA000000 >> 16)
/* EBE20C 801A655C 240DFF80 */  addiu       $t5, $zero, -0x80
/* EBE210 801A6560 244B0008 */  addiu       $t3, $v0, 0x8
/* EBE214 801A6564 ACAB0000 */  sw          $t3, 0x0($a1)
/* EBE218 801A6568 AC4D0004 */  sw          $t5, 0x4($v0)
/* EBE21C 801A656C AC4C0000 */  sw          $t4, 0x0($v0)
/* EBE220 801A6570 0C0015C2 */  jal         Matrix_Push
/* EBE224 801A6574 02002025 */   or         $a0, $s0, $zero
/* EBE228 801A6578 8E2E01BC */  lw          $t6, 0x1BC($s1)
/* EBE22C 801A657C 3C01C348 */  lui         $at, (0xC3480000 >> 16)
/* EBE230 801A6580 44819000 */  mtc1        $at, $ft5
/* EBE234 801A6584 448E5000 */  mtc1        $t6, $ft3
/* EBE238 801A6588 240F0001 */  addiu       $t7, $zero, 0x1
/* EBE23C 801A658C AFAF0010 */  sw          $t7, 0x10($sp)
/* EBE240 801A6590 46805420 */  cvt.s.w     $ft4, $ft3
/* EBE244 801A6594 8E040000 */  lw          $a0, 0x0($s0)
/* EBE248 801A6598 3C05C2C8 */  lui         $a1, (0xC2C80000 >> 16)
/* EBE24C 801A659C 3C06C2C8 */  lui         $a2, (0xC2C80000 >> 16)
/* EBE250 801A65A0 46128100 */  add.s       $ft0, $ft4, $ft5
/* EBE254 801A65A4 44072000 */  mfc1        $a3, $ft0
/* EBE258 801A65A8 0C0016C0 */  jal         Matrix_Translate
/* EBE25C 801A65AC 00000000 */   nop
/* EBE260 801A65B0 3C01801A */  lui         $at, %hi(D_i6_801A7F14)
/* EBE264 801A65B4 C4287F14 */  lwc1        $ft2, %lo(D_i6_801A7F14)($at)
/* EBE268 801A65B8 C62600E8 */  lwc1        $ft1, 0xE8($s1)
/* EBE26C 801A65BC 8E040000 */  lw          $a0, 0x0($s0)
/* EBE270 801A65C0 24060001 */  addiu       $a2, $zero, 0x1
/* EBE274 801A65C4 46083282 */  mul.s       $ft3, $ft1, $ft2
/* EBE278 801A65C8 44055000 */  mfc1        $a1, $ft3
/* EBE27C 801A65CC 0C0017A4 */  jal         Matrix_RotateY
/* EBE280 801A65D0 00000000 */   nop
/* EBE284 801A65D4 C63000E4 */  lwc1        $ft4, 0xE4($s1)
/* EBE288 801A65D8 3C01801A */  lui         $at, %hi(D_i6_801A7F18)
/* EBE28C 801A65DC C4247F18 */  lwc1        $ft0, %lo(D_i6_801A7F18)($at)
/* EBE290 801A65E0 46008487 */  neg.s       $ft5, $ft4
/* EBE294 801A65E4 8E040000 */  lw          $a0, 0x0($s0)
/* EBE298 801A65E8 46049182 */  mul.s       $ft1, $ft5, $ft0
/* EBE29C 801A65EC 24060001 */  addiu       $a2, $zero, 0x1
/* EBE2A0 801A65F0 44053000 */  mfc1        $a1, $ft1
/* EBE2A4 801A65F4 0C001751 */  jal         Matrix_RotateX
/* EBE2A8 801A65F8 00000000 */   nop
/* EBE2AC 801A65FC 44800000 */  mtc1        $zero, $fv0
/* EBE2B0 801A6600 24180001 */  addiu       $t8, $zero, 0x1
/* EBE2B4 801A6604 AFB80010 */  sw          $t8, 0x10($sp)
/* EBE2B8 801A6608 44050000 */  mfc1        $a1, $fv0
/* EBE2BC 801A660C 44060000 */  mfc1        $a2, $fv0
/* EBE2C0 801A6610 8E040000 */  lw          $a0, 0x0($s0)
/* EBE2C4 801A6614 0C0016C0 */  jal         Matrix_Translate
/* EBE2C8 801A6618 3C07C33C */   lui        $a3, (0xC33C0000 >> 16)
/* EBE2CC 801A661C 3C014000 */  lui         $at, (0x40000000 >> 16)
/* EBE2D0 801A6620 44810000 */  mtc1        $at, $fv0
/* EBE2D4 801A6624 24190001 */  addiu       $t9, $zero, 0x1
/* EBE2D8 801A6628 AFB90010 */  sw          $t9, 0x10($sp)
/* EBE2DC 801A662C 44050000 */  mfc1        $a1, $fv0
/* EBE2E0 801A6630 44060000 */  mfc1        $a2, $fv0
/* EBE2E4 801A6634 44070000 */  mfc1        $a3, $fv0
/* EBE2E8 801A6638 0C00170D */  jal         Matrix_Scale
/* EBE2EC 801A663C 8E040000 */   lw         $a0, 0x0($s0)
/* EBE2F0 801A6640 3C048013 */  lui         $a0, %hi(gMasterDisp)
/* EBE2F4 801A6644 0C001BAE */  jal         Matrix_SetGfxMtx
/* EBE2F8 801A6648 24847E64 */   addiu      $a0, $a0, %lo(gMasterDisp)
/* EBE2FC 801A664C 0C0015D0 */  jal         Matrix_Pop
/* EBE300 801A6650 02002025 */   or         $a0, $s0, $zero
/* EBE304 801A6654 0C0015C2 */  jal         Matrix_Push
/* EBE308 801A6658 02002025 */   or         $a0, $s0, $zero
/* EBE30C 801A665C 8E2801BC */  lw          $t0, 0x1BC($s1)
/* EBE310 801A6660 3C01C348 */  lui         $at, (0xC3480000 >> 16)
/* EBE314 801A6664 44818000 */  mtc1        $at, $ft4
/* EBE318 801A6668 44884000 */  mtc1        $t0, $ft2
/* EBE31C 801A666C 24090001 */  addiu       $t1, $zero, 0x1
/* EBE320 801A6670 AFA90010 */  sw          $t1, 0x10($sp)
/* EBE324 801A6674 468042A0 */  cvt.s.w     $ft3, $ft2
/* EBE328 801A6678 8E040000 */  lw          $a0, 0x0($s0)
/* EBE32C 801A667C 3C0542C8 */  lui         $a1, (0x42C80000 >> 16)
/* EBE330 801A6680 3C06C2C8 */  lui         $a2, (0xC2C80000 >> 16)
/* EBE334 801A6684 46105480 */  add.s       $ft5, $ft3, $ft4
/* EBE338 801A6688 44079000 */  mfc1        $a3, $ft5
/* EBE33C 801A668C 0C0016C0 */  jal         Matrix_Translate
/* EBE340 801A6690 00000000 */   nop
/* EBE344 801A6694 3C01801A */  lui         $at, %hi(D_i6_801A7F1C)
/* EBE348 801A6698 C4267F1C */  lwc1        $ft1, %lo(D_i6_801A7F1C)($at)
/* EBE34C 801A669C C62400E8 */  lwc1        $ft0, 0xE8($s1)
/* EBE350 801A66A0 8E040000 */  lw          $a0, 0x0($s0)
/* EBE354 801A66A4 24060001 */  addiu       $a2, $zero, 0x1
/* EBE358 801A66A8 46062202 */  mul.s       $ft2, $ft0, $ft1
/* EBE35C 801A66AC 44054000 */  mfc1        $a1, $ft2
/* EBE360 801A66B0 0C0017A4 */  jal         Matrix_RotateY
/* EBE364 801A66B4 00000000 */   nop
/* EBE368 801A66B8 C62A00E4 */  lwc1        $ft3, 0xE4($s1)
/* EBE36C 801A66BC 3C01801A */  lui         $at, %hi(D_i6_801A7F20)
/* EBE370 801A66C0 C4327F20 */  lwc1        $ft5, %lo(D_i6_801A7F20)($at)
/* EBE374 801A66C4 46005407 */  neg.s       $ft4, $ft3
/* EBE378 801A66C8 8E040000 */  lw          $a0, 0x0($s0)
/* EBE37C 801A66CC 46128102 */  mul.s       $ft0, $ft4, $ft5
/* EBE380 801A66D0 24060001 */  addiu       $a2, $zero, 0x1
/* EBE384 801A66D4 44052000 */  mfc1        $a1, $ft0
/* EBE388 801A66D8 0C001751 */  jal         Matrix_RotateX
/* EBE38C 801A66DC 00000000 */   nop
/* EBE390 801A66E0 44800000 */  mtc1        $zero, $fv0
/* EBE394 801A66E4 240A0001 */  addiu       $t2, $zero, 0x1
/* EBE398 801A66E8 AFAA0010 */  sw          $t2, 0x10($sp)
/* EBE39C 801A66EC 44050000 */  mfc1        $a1, $fv0
/* EBE3A0 801A66F0 44060000 */  mfc1        $a2, $fv0
/* EBE3A4 801A66F4 8E040000 */  lw          $a0, 0x0($s0)
/* EBE3A8 801A66F8 0C0016C0 */  jal         Matrix_Translate
/* EBE3AC 801A66FC 3C07C33C */   lui        $a3, (0xC33C0000 >> 16)
/* EBE3B0 801A6700 3C014000 */  lui         $at, (0x40000000 >> 16)
/* EBE3B4 801A6704 44810000 */  mtc1        $at, $fv0
/* EBE3B8 801A6708 240B0001 */  addiu       $t3, $zero, 0x1
/* EBE3BC 801A670C AFAB0010 */  sw          $t3, 0x10($sp)
/* EBE3C0 801A6710 44050000 */  mfc1        $a1, $fv0
/* EBE3C4 801A6714 44060000 */  mfc1        $a2, $fv0
/* EBE3C8 801A6718 44070000 */  mfc1        $a3, $fv0
/* EBE3CC 801A671C 0C00170D */  jal         Matrix_Scale
/* EBE3D0 801A6720 8E040000 */   lw         $a0, 0x0($s0)
/* EBE3D4 801A6724 3C048013 */  lui         $a0, %hi(gMasterDisp)
/* EBE3D8 801A6728 0C001BAE */  jal         Matrix_SetGfxMtx
/* EBE3DC 801A672C 24847E64 */   addiu      $a0, $a0, %lo(gMasterDisp)
/* EBE3E0 801A6730 0C0015D0 */  jal         Matrix_Pop
/* EBE3E4 801A6734 02002025 */   or         $a0, $s0, $zero
/* EBE3E8 801A6738 8FBF0024 */  lw          $ra, 0x24($sp)
.Li6_801A673C:
/* EBE3EC 801A673C 8FB0001C */  lw          $s0, 0x1C($sp)
/* EBE3F0 801A6740 8FB10020 */  lw          $s1, 0x20($sp)
/* EBE3F4 801A6744 03E00008 */  jr          $ra
/* EBE3F8 801A6748 27BD0028 */   addiu      $sp, $sp, 0x28
/* EBE3FC 801A674C 00000000 */  nop
