#include "sf64dma.h"

#define NO_SEGMENT \
    { NULL, NULL }

#define OVERLAY_OFFSETS(file)                                                                                   \
    {                                                                                                           \
        { SEGMENT_ROM_START(file), SEGMENT_ROM_END(file) }, { SEGMENT_BSS_START(file), SEGMENT_BSS_END(file) }, \
            { SEGMENT_TEXT_START(file), SEGMENT_TEXT_END(file) },                                               \
            { SEGMENT_DATA_START(file), SEGMENT_RODATA_END(file) },                                             \
    }

#define NO_OVERLAY \
    { NO_SEGMENT, NO_SEGMENT, NO_SEGMENT, NO_SEGMENT }

#define ROM_SEGMENT(file) \
    { SEGMENT_ROM_START(file), SEGMENT_ROM_END(file) }

Scene D_800CAFC4[1] = {
    { NO_OVERLAY,
      { /* 1 */ NO_SEGMENT,
        /* 2 */ NO_SEGMENT,
        /* 3 */ NO_SEGMENT,
        /* 4 */ NO_SEGMENT,
        /* 5 */ NO_SEGMENT,
        /* 6 */ NO_SEGMENT,
        /* 7 */ NO_SEGMENT,
        /* 8 */ NO_SEGMENT,
        /* 9 */ NO_SEGMENT,
        /* A */ NO_SEGMENT,
        /* B */ NO_SEGMENT,
        /* C */ NO_SEGMENT,
        /* D */ NO_SEGMENT,
        /* E */ NO_SEGMENT,
        /* F */ ROM_SEGMENT(ast_logo) } },
};

Scene D_800CB05C[6] = {
    { OVERLAY_OFFSETS(ovl_ending),
      { /* 1 */ NO_SEGMENT,
        /* 2 */ NO_SEGMENT,
        /* 3 */ ROM_SEGMENT(ast_arwing),
        /* 4 */ NO_SEGMENT,
        /* 5 */ ROM_SEGMENT(ast_text),
        /* 6 */ NO_SEGMENT,
        /* 7 */ ROM_SEGMENT(ast_ending),
        /* 8 */ NO_SEGMENT,
        /* 9 */ NO_SEGMENT,
        /* A */ NO_SEGMENT,
        /* B */ NO_SEGMENT,
        /* C */ NO_SEGMENT,
        /* D */ ROM_SEGMENT(ast_allies),
        /* E */ ROM_SEGMENT(ast_great_fox),
        /* F */ NO_SEGMENT } },
    { OVERLAY_OFFSETS(ovl_ending),
      { /* 1 */ NO_SEGMENT,
        /* 2 */ NO_SEGMENT,
        /* 3 */ NO_SEGMENT,
        /* 4 */ NO_SEGMENT,
        /* 5 */ ROM_SEGMENT(ast_text),
        /* 6 */ ROM_SEGMENT(ast_title),
        /* 7 */ ROM_SEGMENT(ast_ending),
        /* 8 */ ROM_SEGMENT(ast_ending_award_front),
        /* 9 */ NO_SEGMENT,
        /* A */ NO_SEGMENT,
        /* B */ NO_SEGMENT,
        /* C */ NO_SEGMENT,
        /* D */ NO_SEGMENT,
        /* E */ NO_SEGMENT,
        /* F */ NO_SEGMENT } },
    { OVERLAY_OFFSETS(ovl_ending),
      { /* 1 */ NO_SEGMENT,
        /* 2 */ NO_SEGMENT,
        /* 3 */ NO_SEGMENT,
        /* 4 */ NO_SEGMENT,
        /* 5 */ ROM_SEGMENT(ast_text),
        /* 6 */ ROM_SEGMENT(ast_title),
        /* 7 */ ROM_SEGMENT(ast_ending),
        /* 8 */ ROM_SEGMENT(ast_ending_award_back),
        /* 9 */ NO_SEGMENT,
        /* A */ NO_SEGMENT,
        /* B */ NO_SEGMENT,
        /* C */ NO_SEGMENT,
        /* D */ NO_SEGMENT,
        /* E */ NO_SEGMENT,
        /* F */ NO_SEGMENT } },
    { OVERLAY_OFFSETS(ovl_ending),
      { /* 1 */ NO_SEGMENT,
        /* 2 */ NO_SEGMENT,
        /* 3 */ NO_SEGMENT,
        /* 4 */ NO_SEGMENT,
        /* 5 */ ROM_SEGMENT(ast_text),
        /* 6 */ ROM_SEGMENT(ast_title),
        /* 7 */ ROM_SEGMENT(ast_ending),
        /* 8 */ ROM_SEGMENT(ast_ending_expert),
        /* 9 */ NO_SEGMENT,
        /* A */ NO_SEGMENT,
        /* B */ NO_SEGMENT,
        /* C */ NO_SEGMENT,
        /* D */ NO_SEGMENT,
        /* E */ NO_SEGMENT,
        /* F */ NO_SEGMENT } },
    { OVERLAY_OFFSETS(ovl_ending),
      { /* 1 */ NO_SEGMENT,
        /* 2 */ NO_SEGMENT,
        /* 3 */ NO_SEGMENT,
        /* 4 */ NO_SEGMENT,
        /* 5 */ ROM_SEGMENT(ast_text),
        /* 6 */ ROM_SEGMENT(ast_title),
        /* 7 */ ROM_SEGMENT(ast_ending),
        /* 8 */ NO_SEGMENT,
        /* 9 */ NO_SEGMENT,
        /* A */ NO_SEGMENT,
        /* B */ NO_SEGMENT,
        /* C */ NO_SEGMENT,
        /* D */ NO_SEGMENT,
        /* E */ ROM_SEGMENT(ast_great_fox),
        /* F */ NO_SEGMENT } },
    { OVERLAY_OFFSETS(ovl_ending),
      { /* 1 */ NO_SEGMENT,
        /* 2 */ NO_SEGMENT,
        /* 3 */ ROM_SEGMENT(ast_arwing),
        /* 4 */ NO_SEGMENT,
        /* 5 */ ROM_SEGMENT(ast_text),
        /* 6 */ NO_SEGMENT,
        /* 7 */ ROM_SEGMENT(ast_ending),
        /* 8 */ ROM_SEGMENT(ast_ending_expert),
        /* 9 */ ROM_SEGMENT(ast_font_3d),
        /* A */ NO_SEGMENT,
        /* B */ NO_SEGMENT,
        /* C */ NO_SEGMENT,
        /* D */ NO_SEGMENT,
        /* E */ ROM_SEGMENT(ast_great_fox),
        /* F */ NO_SEGMENT } },
};

Scene D_800CB3EC[1] = {
    { OVERLAY_OFFSETS(ovl_menu),
      { /* 1 */ NO_SEGMENT,
        /* 2 */ NO_SEGMENT,
        /* 3 */ ROM_SEGMENT(ast_arwing),
        /* 4 */ NO_SEGMENT,
        /* 5 */ ROM_SEGMENT(ast_text),
        /* 6 */ ROM_SEGMENT(ast_title),
        /* 7 */ NO_SEGMENT,
        /* 8 */ NO_SEGMENT,
        /* 9 */ NO_SEGMENT,
        /* A */ NO_SEGMENT,
        /* B */ NO_SEGMENT,
        /* C */ NO_SEGMENT,
        /* D */ NO_SEGMENT,
        /* E */ ROM_SEGMENT(ast_great_fox),
        /* F */ NO_SEGMENT } },
};

Scene D_800CB484[3] = {
    { OVERLAY_OFFSETS(ovl_menu),
      { /* 1 */ NO_SEGMENT,
        /* 2 */ NO_SEGMENT,
        /* 3 */ NO_SEGMENT,
        /* 4 */ NO_SEGMENT,
        /* 5 */ ROM_SEGMENT(ast_text),
        /* 6 */ ROM_SEGMENT(ast_map),
        /* 7 */ ROM_SEGMENT(ast_vs_menu),
        /* 8 */ ROM_SEGMENT(ast_option),
        /* 9 */ ROM_SEGMENT(ast_font_3d),
        /* A */ ROM_SEGMENT(ast_option_en),
        /* B */ ROM_SEGMENT(ast_map_en),
        /* C */ ROM_SEGMENT(ast_vs_menu_en),
        /* D */ NO_SEGMENT,
        /* E */ NO_SEGMENT,
        /* F */ NO_SEGMENT } },
    { OVERLAY_OFFSETS(ovl_menu),
      { /* 1 */ NO_SEGMENT,
        /* 2 */ NO_SEGMENT,
        /* 3 */ NO_SEGMENT,
        /* 4 */ NO_SEGMENT,
        /* 5 */ ROM_SEGMENT(ast_text),
        /* 6 */ ROM_SEGMENT(ast_map),
        /* 7 */ ROM_SEGMENT(ast_vs_menu),
        /* 8 */ ROM_SEGMENT(ast_option),
        /* 9 */ ROM_SEGMENT(ast_font_3d),
        /* A */ ROM_SEGMENT(ast_option_fr),
        /* B */ ROM_SEGMENT(ast_map_fr),
        /* C */ ROM_SEGMENT(ast_vs_menu_fr),
        /* D */ NO_SEGMENT,
        /* E */ NO_SEGMENT,
        /* F */ NO_SEGMENT } },
    { OVERLAY_OFFSETS(ovl_menu),
      { /* 1 */ NO_SEGMENT,
        /* 2 */ NO_SEGMENT,
        /* 3 */ NO_SEGMENT,
        /* 4 */ NO_SEGMENT,
        /* 5 */ ROM_SEGMENT(ast_text),
        /* 6 */ ROM_SEGMENT(ast_map),
        /* 7 */ ROM_SEGMENT(ast_vs_menu),
        /* 8 */ ROM_SEGMENT(ast_option),
        /* 9 */ ROM_SEGMENT(ast_font_3d),
        /* A */ ROM_SEGMENT(ast_option_de),
        /* B */ ROM_SEGMENT(ast_map_de),
        /* C */ ROM_SEGMENT(ast_vs_menu_de),
        /* D */ NO_SEGMENT,
        /* E */ NO_SEGMENT,
        /* F */ NO_SEGMENT } },
};

Scene D_800CB64C[3] = {
    { OVERLAY_OFFSETS(ovl_menu),
      { /* 1 */ NO_SEGMENT,
        /* 2 */ NO_SEGMENT,
        /* 3 */ ROM_SEGMENT(ast_arwing),
        /* 4 */ NO_SEGMENT,
        /* 5 */ ROM_SEGMENT(ast_text),
        /* 6 */ ROM_SEGMENT(ast_map),
        /* 7 */ NO_SEGMENT,
        /* 8 */ NO_SEGMENT,
        /* 9 */ ROM_SEGMENT(ast_font_3d),
        /* A */ NO_SEGMENT,
        /* B */ ROM_SEGMENT(ast_map_en),
        /* C */ NO_SEGMENT,
        /* D */ NO_SEGMENT,
        /* E */ NO_SEGMENT,
        /* F */ NO_SEGMENT } },
    { OVERLAY_OFFSETS(ovl_menu),
      { /* 1 */ NO_SEGMENT,
        /* 2 */ NO_SEGMENT,
        /* 3 */ ROM_SEGMENT(ast_arwing),
        /* 4 */ NO_SEGMENT,
        /* 5 */ ROM_SEGMENT(ast_text),
        /* 6 */ ROM_SEGMENT(ast_map),
        /* 7 */ NO_SEGMENT,
        /* 8 */ NO_SEGMENT,
        /* 9 */ ROM_SEGMENT(ast_font_3d),
        /* A */ NO_SEGMENT,
        /* B */ ROM_SEGMENT(ast_map_fr),
        /* C */ NO_SEGMENT,
        /* D */ NO_SEGMENT,
        /* E */ NO_SEGMENT,
        /* F */ NO_SEGMENT } },
    { OVERLAY_OFFSETS(ovl_menu),
      { /* 1 */ NO_SEGMENT,
        /* 2 */ NO_SEGMENT,
        /* 3 */ ROM_SEGMENT(ast_arwing),
        /* 4 */ NO_SEGMENT,
        /* 5 */ ROM_SEGMENT(ast_text),
        /* 6 */ ROM_SEGMENT(ast_map),
        /* 7 */ NO_SEGMENT,
        /* 8 */ NO_SEGMENT,
        /* 9 */ ROM_SEGMENT(ast_font_3d),
        /* A */ NO_SEGMENT,
        /* B */ ROM_SEGMENT(ast_map_de),
        /* C */ NO_SEGMENT,
        /* D */ NO_SEGMENT,
        /* E */ NO_SEGMENT,
        /* F */ NO_SEGMENT } },
};

Scene D_800CB814[1] = {
    { OVERLAY_OFFSETS(ovl_menu),
      { /* 1 */ NO_SEGMENT,
        /* 2 */ NO_SEGMENT,
        /* 3 */ NO_SEGMENT,
        /* 4 */ NO_SEGMENT,
        /* 5 */ ROM_SEGMENT(ast_text),
        /* 6 */ NO_SEGMENT,
        /* 7 */ NO_SEGMENT,
        /* 8 */ NO_SEGMENT,
        /* 9 */ NO_SEGMENT,
        /* A */ NO_SEGMENT,
        /* B */ NO_SEGMENT,
        /* C */ ROM_SEGMENT(ast_andross),
        /* D */ NO_SEGMENT,
        /* E */ NO_SEGMENT,
        /* F */ NO_SEGMENT } },
};

Scene D_800CB8AC[1] = {
    { OVERLAY_OFFSETS(ovl_i1),
      { /* 1 */ ROM_SEGMENT(ast_common),
        /* 2 */ ROM_SEGMENT(ast_bg_planet),
        /* 3 */ ROM_SEGMENT(ast_arwing),
        /* 4 */ ROM_SEGMENT(ast_enmy_planet),
        /* 5 */ ROM_SEGMENT(ast_text),
        /* 6 */ ROM_SEGMENT(ast_corneria),
        /* 7 */ NO_SEGMENT,
        /* 8 */ NO_SEGMENT,
        /* 9 */ NO_SEGMENT,
        /* A */ NO_SEGMENT,
        /* B */ NO_SEGMENT,
        /* C */ NO_SEGMENT,
        /* D */ NO_SEGMENT,
        /* E */ NO_SEGMENT,
        /* F */ NO_SEGMENT } },
};

Scene D_800CB944[2] = {
    { OVERLAY_OFFSETS(ovl_i2),
      { /* 1 */ ROM_SEGMENT(ast_common),
        /* 2 */ ROM_SEGMENT(ast_bg_space),
        /* 3 */ ROM_SEGMENT(ast_arwing),
        /* 4 */ ROM_SEGMENT(ast_enmy_space),
        /* 5 */ ROM_SEGMENT(ast_text),
        /* 6 */ ROM_SEGMENT(ast_meteo),
        /* 7 */ ROM_SEGMENT(ast_warp_zone),
        /* 8 */ NO_SEGMENT,
        /* 9 */ NO_SEGMENT,
        /* A */ NO_SEGMENT,
        /* B */ NO_SEGMENT,
        /* C */ NO_SEGMENT,
        /* D */ NO_SEGMENT,
        /* E */ ROM_SEGMENT(ast_great_fox),
        /* F */ NO_SEGMENT } },
    { OVERLAY_OFFSETS(ovl_i2),
      { /* 1 */ ROM_SEGMENT(ast_common),
        /* 2 */ ROM_SEGMENT(ast_bg_space),
        /* 3 */ ROM_SEGMENT(ast_arwing),
        /* 4 */ ROM_SEGMENT(ast_enmy_space),
        /* 5 */ ROM_SEGMENT(ast_text),
        /* 6 */ ROM_SEGMENT(ast_meteo),
        /* 7 */ ROM_SEGMENT(ast_warp_zone),
        /* 8 */ NO_SEGMENT,
        /* 9 */ NO_SEGMENT,
        /* A */ NO_SEGMENT,
        /* B */ NO_SEGMENT,
        /* C */ NO_SEGMENT,
        /* D */ NO_SEGMENT,
        /* E */ ROM_SEGMENT(ast_great_fox),
        /* F */ NO_SEGMENT } },
};

Scene D_800CBA74[6] = {
    { OVERLAY_OFFSETS(ovl_i5),
      { /* 1 */ ROM_SEGMENT(ast_common),
        /* 2 */ ROM_SEGMENT(ast_bg_planet),
        /* 3 */ ROM_SEGMENT(ast_landmaster),
        /* 4 */ ROM_SEGMENT(ast_enmy_planet),
        /* 5 */ ROM_SEGMENT(ast_text),
        /* 6 */ ROM_SEGMENT(ast_titania),
        /* 7 */ ROM_SEGMENT(ast_7_ti_1),
        /* 8 */ NO_SEGMENT,
        /* 9 */ NO_SEGMENT,
        /* A */ NO_SEGMENT,
        /* B */ NO_SEGMENT,
        /* C */ NO_SEGMENT,
        /* D */ NO_SEGMENT,
        /* E */ ROM_SEGMENT(ast_great_fox),
        /* F */ NO_SEGMENT } },
    { OVERLAY_OFFSETS(ovl_i5),
      { /* 1 */ ROM_SEGMENT(ast_common),
        /* 2 */ ROM_SEGMENT(ast_bg_planet),
        /* 3 */ ROM_SEGMENT(ast_landmaster),
        /* 4 */ ROM_SEGMENT(ast_enmy_planet),
        /* 5 */ ROM_SEGMENT(ast_text),
        /* 6 */ ROM_SEGMENT(ast_titania),
        /* 7 */ ROM_SEGMENT(ast_7_ti_2),
        /* 8 */ NO_SEGMENT,
        /* 9 */ NO_SEGMENT,
        /* A */ NO_SEGMENT,
        /* B */ NO_SEGMENT,
        /* C */ NO_SEGMENT,
        /* D */ NO_SEGMENT,
        /* E */ NO_SEGMENT,
        /* F */ NO_SEGMENT } },
    { OVERLAY_OFFSETS(ovl_i5),
      { /* 1 */ ROM_SEGMENT(ast_common),
        /* 2 */ ROM_SEGMENT(ast_bg_planet),
        /* 3 */ ROM_SEGMENT(ast_landmaster),
        /* 4 */ ROM_SEGMENT(ast_enmy_planet),
        /* 5 */ ROM_SEGMENT(ast_text),
        /* 6 */ ROM_SEGMENT(ast_titania),
        /* 7 */ ROM_SEGMENT(ast_7_ti_2),
        /* 8 */ ROM_SEGMENT(ast_8_ti),
        /* 9 */ NO_SEGMENT,
        /* A */ NO_SEGMENT,
        /* B */ NO_SEGMENT,
        /* C */ NO_SEGMENT,
        /* D */ NO_SEGMENT,
        /* E */ NO_SEGMENT,
        /* F */ NO_SEGMENT } },
    { OVERLAY_OFFSETS(ovl_i5),
      { /* 1 */ ROM_SEGMENT(ast_common),
        /* 2 */ ROM_SEGMENT(ast_bg_planet),
        /* 3 */ ROM_SEGMENT(ast_landmaster),
        /* 4 */ ROM_SEGMENT(ast_enmy_planet),
        /* 5 */ ROM_SEGMENT(ast_text),
        /* 6 */ ROM_SEGMENT(ast_titania),
        /* 7 */ ROM_SEGMENT(ast_7_ti_2),
        /* 8 */ ROM_SEGMENT(ast_8_ti),
        /* 9 */ ROM_SEGMENT(ast_9_ti),
        /* A */ NO_SEGMENT,
        /* B */ NO_SEGMENT,
        /* C */ NO_SEGMENT,
        /* D */ NO_SEGMENT,
        /* E */ NO_SEGMENT,
        /* F */ NO_SEGMENT } },
    { OVERLAY_OFFSETS(ovl_i5),
      { /* 1 */ ROM_SEGMENT(ast_common),
        /* 2 */ ROM_SEGMENT(ast_bg_planet),
        /* 3 */ ROM_SEGMENT(ast_landmaster),
        /* 4 */ ROM_SEGMENT(ast_enmy_planet),
        /* 5 */ ROM_SEGMENT(ast_text),
        /* 6 */ ROM_SEGMENT(ast_titania),
        /* 7 */ ROM_SEGMENT(ast_7_ti_2),
        /* 8 */ ROM_SEGMENT(ast_8_ti),
        /* 9 */ ROM_SEGMENT(ast_9_ti),
        /* A */ ROM_SEGMENT(ast_A_ti),
        /* B */ NO_SEGMENT,
        /* C */ NO_SEGMENT,
        /* D */ NO_SEGMENT,
        /* E */ NO_SEGMENT,
        /* F */ NO_SEGMENT } },
    { OVERLAY_OFFSETS(ovl_i5),
      { /* 1 */ ROM_SEGMENT(ast_common),
        /* 2 */ ROM_SEGMENT(ast_bg_planet),
        /* 3 */ ROM_SEGMENT(ast_landmaster),
        /* 4 */ ROM_SEGMENT(ast_enmy_planet),
        /* 5 */ ROM_SEGMENT(ast_text),
        /* 6 */ ROM_SEGMENT(ast_titania),
        /* 7 */ ROM_SEGMENT(ast_7_ti_2),
        /* 8 */ ROM_SEGMENT(ast_8_ti),
        /* 9 */ ROM_SEGMENT(ast_9_ti),
        /* A */ ROM_SEGMENT(ast_A_ti),
        /* B */ NO_SEGMENT,
        /* C */ NO_SEGMENT,
        /* D */ NO_SEGMENT,
        /* E */ ROM_SEGMENT(ast_great_fox),
        /* F */ NO_SEGMENT } },
};

Scene D_800CBE04[2] = {
    { OVERLAY_OFFSETS(ovl_i2),
      { /* 1 */ ROM_SEGMENT(ast_common),
        /* 2 */ ROM_SEGMENT(ast_bg_space),
        /* 3 */ ROM_SEGMENT(ast_arwing),
        /* 4 */ ROM_SEGMENT(ast_enmy_space),
        /* 5 */ ROM_SEGMENT(ast_text),
        /* 6 */ ROM_SEGMENT(ast_sector_x),
        /* 7 */ ROM_SEGMENT(ast_warp_zone),
        /* 8 */ NO_SEGMENT,
        /* 9 */ NO_SEGMENT,
        /* A */ NO_SEGMENT,
        /* B */ NO_SEGMENT,
        /* C */ NO_SEGMENT,
        /* D */ ROM_SEGMENT(ast_allies),
        /* E */ NO_SEGMENT,
        /* F */ NO_SEGMENT } },
    { OVERLAY_OFFSETS(ovl_i2),
      { /* 1 */ ROM_SEGMENT(ast_common),
        /* 2 */ ROM_SEGMENT(ast_bg_space),
        /* 3 */ ROM_SEGMENT(ast_arwing),
        /* 4 */ ROM_SEGMENT(ast_enmy_space),
        /* 5 */ ROM_SEGMENT(ast_text),
        /* 6 */ ROM_SEGMENT(ast_sector_x),
        /* 7 */ ROM_SEGMENT(ast_warp_zone),
        /* 8 */ NO_SEGMENT,
        /* 9 */ NO_SEGMENT,
        /* A */ NO_SEGMENT,
        /* B */ NO_SEGMENT,
        /* C */ NO_SEGMENT,
        /* D */ ROM_SEGMENT(ast_allies),
        /* E */ ROM_SEGMENT(ast_great_fox),
        /* F */ NO_SEGMENT } },
};

Scene D_800CBF34[1] = {
    { OVERLAY_OFFSETS(ovl_i4),
      { /* 1 */ ROM_SEGMENT(ast_common),
        /* 2 */ ROM_SEGMENT(ast_bg_space),
        /* 3 */ ROM_SEGMENT(ast_arwing),
        /* 4 */ ROM_SEGMENT(ast_enmy_space),
        /* 5 */ ROM_SEGMENT(ast_text),
        /* 6 */ ROM_SEGMENT(ast_sector_z),
        /* 7 */ NO_SEGMENT,
        /* 8 */ NO_SEGMENT,
        /* 9 */ NO_SEGMENT,
        /* A */ NO_SEGMENT,
        /* B */ NO_SEGMENT,
        /* C */ NO_SEGMENT,
        /* D */ ROM_SEGMENT(ast_allies),
        /* E */ ROM_SEGMENT(ast_great_fox),
        /* F */ NO_SEGMENT } },
};

Scene D_800CBFCC[1] = {
    { OVERLAY_OFFSETS(ovl_i3),
      { /* 1 */ ROM_SEGMENT(ast_common),
        /* 2 */ ROM_SEGMENT(ast_bg_planet),
        /* 3 */ ROM_SEGMENT(ast_blue_marine),
        /* 4 */ ROM_SEGMENT(ast_enmy_planet),
        /* 5 */ ROM_SEGMENT(ast_text),
        /* 6 */ ROM_SEGMENT(ast_aquas),
        /* 7 */ NO_SEGMENT,
        /* 8 */ NO_SEGMENT,
        /* 9 */ NO_SEGMENT,
        /* A */ NO_SEGMENT,
        /* B */ NO_SEGMENT,
        /* C */ NO_SEGMENT,
        /* D */ NO_SEGMENT,
        /* E */ ROM_SEGMENT(ast_great_fox),
        /* F */ NO_SEGMENT } },
};

Scene D_800CC064[1] = {
    { OVERLAY_OFFSETS(ovl_i3),
      { /* 1 */ ROM_SEGMENT(ast_common),
        /* 2 */ ROM_SEGMENT(ast_bg_space),
        /* 3 */ ROM_SEGMENT(ast_arwing),
        /* 4 */ ROM_SEGMENT(ast_enmy_space),
        /* 5 */ ROM_SEGMENT(ast_text),
        /* 6 */ ROM_SEGMENT(ast_area_6),
        /* 7 */ NO_SEGMENT,
        /* 8 */ NO_SEGMENT,
        /* 9 */ NO_SEGMENT,
        /* A */ NO_SEGMENT,
        /* B */ NO_SEGMENT,
        /* C */ NO_SEGMENT,
        /* D */ NO_SEGMENT,
        /* E */ ROM_SEGMENT(ast_great_fox),
        /* F */ NO_SEGMENT } },
};

Scene D_800CC0FC[2] = {
    { OVERLAY_OFFSETS(ovl_i4),
      { /* 1 */ ROM_SEGMENT(ast_common),
        /* 2 */ ROM_SEGMENT(ast_bg_planet),
        /* 3 */ ROM_SEGMENT(ast_arwing),
        /* 4 */ ROM_SEGMENT(ast_enmy_planet),
        /* 5 */ ROM_SEGMENT(ast_text),
        /* 6 */ ROM_SEGMENT(ast_fortuna),
        /* 7 */ NO_SEGMENT,
        /* 8 */ NO_SEGMENT,
        /* 9 */ NO_SEGMENT,
        /* A */ NO_SEGMENT,
        /* B */ NO_SEGMENT,
        /* C */ NO_SEGMENT,
        /* D */ NO_SEGMENT,
        /* E */ NO_SEGMENT,
        /* F */ ROM_SEGMENT(ast_star_wolf) } },
    { OVERLAY_OFFSETS(ovl_i4),
      { /* 1 */ ROM_SEGMENT(ast_common),
        /* 2 */ ROM_SEGMENT(ast_bg_planet),
        /* 3 */ ROM_SEGMENT(ast_arwing),
        /* 4 */ ROM_SEGMENT(ast_enmy_planet),
        /* 5 */ ROM_SEGMENT(ast_text),
        /* 6 */ ROM_SEGMENT(ast_fortuna),
        /* 7 */ NO_SEGMENT,
        /* 8 */ NO_SEGMENT,
        /* 9 */ NO_SEGMENT,
        /* A */ NO_SEGMENT,
        /* B */ NO_SEGMENT,
        /* C */ NO_SEGMENT,
        /* D */ NO_SEGMENT,
        /* E */ ROM_SEGMENT(ast_great_fox),
        /* F */ NO_SEGMENT } },
};

Scene D_800CC22C[1] = {
    { OVERLAY_OFFSETS(ovl_i3),
      { /* 1 */ ROM_SEGMENT(ast_common),
        /* 2 */ ROM_SEGMENT(ast_bg_space),
        /* 3 */ ROM_SEGMENT(ast_arwing),
        /* 4 */ ROM_SEGMENT(ast_enmy_space),
        /* 5 */ ROM_SEGMENT(ast_text),
        /* 6 */ ROM_SEGMENT(ast_area_6),
        /* 7 */ NO_SEGMENT,
        /* 8 */ NO_SEGMENT,
        /* 9 */ NO_SEGMENT,
        /* A */ NO_SEGMENT,
        /* B */ NO_SEGMENT,
        /* C */ NO_SEGMENT,
        /* D */ NO_SEGMENT,
        /* E */ ROM_SEGMENT(ast_great_fox),
        /* F */ NO_SEGMENT } },
};

Scene D_800CC2C4[1] = {
    { OVERLAY_OFFSETS(ovl_i6),
      { /* 1 */ ROM_SEGMENT(ast_common),
        /* 2 */ ROM_SEGMENT(ast_bg_space),
        /* 3 */ ROM_SEGMENT(ast_arwing),
        /* 4 */ ROM_SEGMENT(ast_enmy_space),
        /* 5 */ ROM_SEGMENT(ast_text),
        /* 6 */ ROM_SEGMENT(ast_sector_y),
        /* 7 */ NO_SEGMENT,
        /* 8 */ NO_SEGMENT,
        /* 9 */ NO_SEGMENT,
        /* A */ NO_SEGMENT,
        /* B */ NO_SEGMENT,
        /* C */ NO_SEGMENT,
        /* D */ NO_SEGMENT,
        /* E */ NO_SEGMENT,
        /* F */ NO_SEGMENT } },
};

Scene D_800CC35C[1] = {
    { OVERLAY_OFFSETS(ovl_i3),
      { /* 1 */ ROM_SEGMENT(ast_common),
        /* 2 */ ROM_SEGMENT(ast_bg_planet),
        /* 3 */ ROM_SEGMENT(ast_arwing),
        /* 4 */ ROM_SEGMENT(ast_enmy_planet),
        /* 5 */ ROM_SEGMENT(ast_text),
        /* 6 */ ROM_SEGMENT(ast_solar),
        /* 7 */ NO_SEGMENT,
        /* 8 */ NO_SEGMENT,
        /* 9 */ NO_SEGMENT,
        /* A */ NO_SEGMENT,
        /* B */ NO_SEGMENT,
        /* C */ NO_SEGMENT,
        /* D */ ROM_SEGMENT(ast_allies),
        /* E */ NO_SEGMENT,
        /* F */ NO_SEGMENT } },
};

Scene D_800CC3F4[1] = {
    { OVERLAY_OFFSETS(ovl_i3),
      { /* 1 */ ROM_SEGMENT(ast_common),
        /* 2 */ ROM_SEGMENT(ast_bg_planet),
        /* 3 */ ROM_SEGMENT(ast_arwing),
        /* 4 */ ROM_SEGMENT(ast_enmy_planet),
        /* 5 */ ROM_SEGMENT(ast_text),
        /* 6 */ ROM_SEGMENT(ast_zoness),
        /* 7 */ NO_SEGMENT,
        /* 8 */ NO_SEGMENT,
        /* 9 */ NO_SEGMENT,
        /* A */ NO_SEGMENT,
        /* B */ NO_SEGMENT,
        /* C */ NO_SEGMENT,
        /* D */ ROM_SEGMENT(ast_allies),
        /* E */ NO_SEGMENT,
        /* F */ NO_SEGMENT } },
};

Scene D_800CC48C[1] = {
    { OVERLAY_OFFSETS(ovl_i1),
      { /* 1 */ ROM_SEGMENT(ast_common),
        /* 2 */ ROM_SEGMENT(ast_bg_planet),
        /* 3 */ ROM_SEGMENT(ast_arwing),
        /* 4 */ ROM_SEGMENT(ast_enmy_planet),
        /* 5 */ ROM_SEGMENT(ast_text),
        /* 6 */ ROM_SEGMENT(ast_venom_1),
        /* 7 */ NO_SEGMENT,
        /* 8 */ NO_SEGMENT,
        /* 9 */ ROM_SEGMENT(ast_ve1_boss),
        /* A */ NO_SEGMENT,
        /* B */ NO_SEGMENT,
        /* C */ NO_SEGMENT,
        /* D */ ROM_SEGMENT(ast_allies),
        /* E */ NO_SEGMENT,
        /* F */ NO_SEGMENT } },
};

Scene D_800CC524[1] = {
    { OVERLAY_OFFSETS(ovl_i6),
      { /* 1 */ ROM_SEGMENT(ast_common),
        /* 2 */ ROM_SEGMENT(ast_bg_planet),
        /* 3 */ ROM_SEGMENT(ast_arwing),
        /* 4 */ NO_SEGMENT,
        /* 5 */ ROM_SEGMENT(ast_text),
        /* 6 */ ROM_SEGMENT(ast_venom_2),
        /* 7 */ NO_SEGMENT,
        /* 8 */ NO_SEGMENT,
        /* 9 */ NO_SEGMENT,
        /* A */ NO_SEGMENT,
        /* B */ NO_SEGMENT,
        /* C */ ROM_SEGMENT(ast_andross),
        /* D */ ROM_SEGMENT(ast_allies),
        /* E */ NO_SEGMENT,
        /* F */ NO_SEGMENT } },
};

Scene D_800CC5BC[2] = {
    { OVERLAY_OFFSETS(ovl_i6),
      { /* 1 */ ROM_SEGMENT(ast_common),
        /* 2 */ ROM_SEGMENT(ast_bg_planet),
        /* 3 */ ROM_SEGMENT(ast_arwing),
        /* 4 */ ROM_SEGMENT(ast_enmy_planet),
        /* 5 */ ROM_SEGMENT(ast_text),
        /* 6 */ ROM_SEGMENT(ast_venom_2),
        /* 7 */ NO_SEGMENT,
        /* 8 */ NO_SEGMENT,
        /* 9 */ NO_SEGMENT,
        /* A */ NO_SEGMENT,
        /* B */ NO_SEGMENT,
        /* C */ NO_SEGMENT,
        /* D */ NO_SEGMENT,
        /* E */ NO_SEGMENT,
        /* F */ ROM_SEGMENT(ast_star_wolf) } },
    { OVERLAY_OFFSETS(ovl_i6),
      { /* 1 */ ROM_SEGMENT(ast_common),
        /* 2 */ ROM_SEGMENT(ast_bg_planet),
        /* 3 */ ROM_SEGMENT(ast_arwing),
        /* 4 */ ROM_SEGMENT(ast_enmy_planet),
        /* 5 */ ROM_SEGMENT(ast_text),
        /* 6 */ ROM_SEGMENT(ast_venom_2),
        /* 7 */ NO_SEGMENT,
        /* 8 */ NO_SEGMENT,
        /* 9 */ NO_SEGMENT,
        /* A */ NO_SEGMENT,
        /* B */ NO_SEGMENT,
        /* C */ NO_SEGMENT,
        /* D */ NO_SEGMENT,
        /* E */ ROM_SEGMENT(ast_great_fox),
        /* F */ NO_SEGMENT } },
};

Scene D_800CC6EC[1] = {
    { OVERLAY_OFFSETS(ovl_i2),
      { /* 1 */ ROM_SEGMENT(ast_common),
        /* 2 */ ROM_SEGMENT(ast_bg_planet),
        /* 3 */ ROM_SEGMENT(ast_arwing),
        /* 4 */ ROM_SEGMENT(ast_enmy_planet),
        /* 5 */ ROM_SEGMENT(ast_text),
        /* 6 */ ROM_SEGMENT(ast_ve1_boss),
        /* 7 */ NO_SEGMENT,
        /* 8 */ NO_SEGMENT,
        /* 9 */ NO_SEGMENT,
        /* A */ NO_SEGMENT,
        /* B */ NO_SEGMENT,
        /* C */ NO_SEGMENT,
        /* D */ NO_SEGMENT,
        /* E */ NO_SEGMENT,
        /* F */ NO_SEGMENT } },
};

Scene D_800CC784[1] = {
    { OVERLAY_OFFSETS(ovl_i4),
      { /* 1 */ ROM_SEGMENT(ast_common),
        /* 2 */ ROM_SEGMENT(ast_bg_space),
        /* 3 */ ROM_SEGMENT(ast_arwing),
        /* 4 */ ROM_SEGMENT(ast_enmy_space),
        /* 5 */ ROM_SEGMENT(ast_text),
        /* 6 */ ROM_SEGMENT(ast_bolse),
        /* 7 */ NO_SEGMENT,
        /* 8 */ NO_SEGMENT,
        /* 9 */ NO_SEGMENT,
        /* A */ NO_SEGMENT,
        /* B */ NO_SEGMENT,
        /* C */ NO_SEGMENT,
        /* D */ NO_SEGMENT,
        /* E */ NO_SEGMENT,
        /* F */ ROM_SEGMENT(ast_star_wolf) } },
};

Scene D_800CC81C[1] = {
    { OVERLAY_OFFSETS(ovl_i4),
      { /* 1 */ ROM_SEGMENT(ast_common),
        /* 2 */ ROM_SEGMENT(ast_bg_planet),
        /* 3 */ ROM_SEGMENT(ast_arwing),
        /* 4 */ ROM_SEGMENT(ast_enmy_planet),
        /* 5 */ ROM_SEGMENT(ast_text),
        /* 6 */ ROM_SEGMENT(ast_katina),
        /* 7 */ NO_SEGMENT,
        /* 8 */ NO_SEGMENT,
        /* 9 */ NO_SEGMENT,
        /* A */ NO_SEGMENT,
        /* B */ NO_SEGMENT,
        /* C */ NO_SEGMENT,
        /* D */ ROM_SEGMENT(ast_allies),
        /* E */ NO_SEGMENT,
        /* F */ ROM_SEGMENT(ast_star_wolf) } },
};

Scene D_800CC8B4[2] = {
    { OVERLAY_OFFSETS(ovl_i5),
      { /* 1 */ ROM_SEGMENT(ast_common),
        /* 2 */ ROM_SEGMENT(ast_bg_planet),
        /* 3 */ ROM_SEGMENT(ast_landmaster),
        /* 4 */ ROM_SEGMENT(ast_enmy_planet),
        /* 5 */ ROM_SEGMENT(ast_text),
        /* 6 */ ROM_SEGMENT(ast_macbeth),
        /* 7 */ NO_SEGMENT,
        /* 8 */ NO_SEGMENT,
        /* 9 */ NO_SEGMENT,
        /* A */ NO_SEGMENT,
        /* B */ NO_SEGMENT,
        /* C */ NO_SEGMENT,
        /* D */ ROM_SEGMENT(ast_allies),
        /* E */ NO_SEGMENT,
        /* F */ NO_SEGMENT } },
    { OVERLAY_OFFSETS(ovl_i5),
      { /* 1 */ ROM_SEGMENT(ast_common),
        /* 2 */ ROM_SEGMENT(ast_bg_planet),
        /* 3 */ ROM_SEGMENT(ast_landmaster),
        /* 4 */ ROM_SEGMENT(ast_enmy_planet),
        /* 5 */ ROM_SEGMENT(ast_text),
        /* 6 */ ROM_SEGMENT(ast_macbeth),
        /* 7 */ NO_SEGMENT,
        /* 8 */ NO_SEGMENT,
        /* 9 */ NO_SEGMENT,
        /* A */ NO_SEGMENT,
        /* B */ NO_SEGMENT,
        /* C */ NO_SEGMENT,
        /* D */ NO_SEGMENT,
        /* E */ ROM_SEGMENT(ast_great_fox),
        /* F */ NO_SEGMENT } },
};

Scene D_800CC9E4[1] = {
    { OVERLAY_OFFSETS(ovl_i1),
      { /* 1 */ ROM_SEGMENT(ast_common),
        /* 2 */ ROM_SEGMENT(ast_bg_planet),
        /* 3 */ ROM_SEGMENT(ast_arwing),
        /* 4 */ ROM_SEGMENT(ast_enmy_planet),
        /* 5 */ ROM_SEGMENT(ast_text),
        /* 6 */ ROM_SEGMENT(ast_training),
        /* 7 */ NO_SEGMENT,
        /* 8 */ NO_SEGMENT,
        /* 9 */ NO_SEGMENT,
        /* A */ NO_SEGMENT,
        /* B */ NO_SEGMENT,
        /* C */ NO_SEGMENT,
        /* D */ NO_SEGMENT,
        /* E */ NO_SEGMENT,
        /* F */ ROM_SEGMENT(ast_star_wolf) } },
};

Scene D_800CCA7C[2] = {
    { OVERLAY_OFFSETS(ovl_i2),
      { /* 1 */ ROM_SEGMENT(ast_common),
        /* 2 */ ROM_SEGMENT(ast_bg_planet),
        /* 3 */ ROM_SEGMENT(ast_versus),
        /* 4 */ ROM_SEGMENT(ast_enmy_planet),
        /* 5 */ ROM_SEGMENT(ast_text),
        /* 6 */ NO_SEGMENT,
        /* 7 */ ROM_SEGMENT(ast_vs_menu),
        /* 8 */ NO_SEGMENT,
        /* 9 */ NO_SEGMENT,
        /* A */ NO_SEGMENT,
        /* B */ NO_SEGMENT,
        /* C */ NO_SEGMENT,
        /* D */ NO_SEGMENT,
        /* E */ NO_SEGMENT,
        /* F */ NO_SEGMENT } },
    { OVERLAY_OFFSETS(ovl_i2),
      { /* 1 */ ROM_SEGMENT(ast_common),
        /* 2 */ ROM_SEGMENT(ast_bg_space),
        /* 3 */ ROM_SEGMENT(ast_versus),
        /* 4 */ ROM_SEGMENT(ast_enmy_space),
        /* 5 */ ROM_SEGMENT(ast_text),
        /* 6 */ NO_SEGMENT,
        /* 7 */ ROM_SEGMENT(ast_vs_menu),
        /* 8 */ NO_SEGMENT,
        /* 9 */ NO_SEGMENT,
        /* A */ NO_SEGMENT,
        /* B */ NO_SEGMENT,
        /* C */ NO_SEGMENT,
        /* D */ NO_SEGMENT,
        /* E */ NO_SEGMENT,
        /* F */ NO_SEGMENT } },
};

Scene sOvlUnused_Unk[1] = {
    { OVERLAY_OFFSETS(ovl_unused),
      { /* 0x1 */ NO_SEGMENT,
        /* 0x2 */ NO_SEGMENT,
        /* 0x3 */ NO_SEGMENT,
        /* 0x4 */ NO_SEGMENT,
        /* 0x5 */ NO_SEGMENT,
        /* 0x6 */ NO_SEGMENT,
        /* 0x7 */ NO_SEGMENT,
        /* 0x8 */ NO_SEGMENT,
        /* 0x9 */ NO_SEGMENT,
        /* 0xA */ NO_SEGMENT,
        /* 0xB */ NO_SEGMENT,
        /* 0xC */ NO_SEGMENT,
        /* 0xD */ NO_SEGMENT,
        /* 0xE */ NO_SEGMENT,
        /* 0xF */ NO_SEGMENT } },
};
