#ifndef SF64_ACTOR_DEBRIS_H
#define SF64_ACTOR_DEBRIS_H

typedef enum ActorDebrisType {
    ACTORDEBRIS_0,
    ACTORDEBRIS_1,
    ACTORDEBRIS_2,
    ACTORDEBRIS_3,
    ACTORDEBRIS_4,
    ACTORDEBRIS_39 = 39,
    ACTORDEBRIS_40,
    ACTORDEBRIS_41,
    ACTORDEBRIS_42,
    ACTORDEBRIS_43,
    ACTORDEBRIS_44,
    ACTORDEBRIS_45,
    ACTORDEBRIS_46,
    ACTORDEBRIS_47,
    ACTORDEBRIS_48,
    ACTORDEBRIS_49,
    ACTORDEBRIS_50,
    ACTORDEBRIS_51,
    ACTORDEBRIS_52,
    ACTORDEBRIS_53,
    ACTORDEBRIS_54,
    ACTORDEBRIS_55,
    ACTORDEBRIS_56,
    ACTORDEBRIS_57,
    ACTORDEBRIS_58,
    ACTORDEBRIS_59,
    ACTORDEBRIS_70 = 70,
} ActorDebrisType;

#endif
