compiler_type = "ido"

[preserve_macros]
"g[DS]P.*" = "void"
"gs[DS]P.*" = "void"
"G_.*" = "int"
"M_.*" = "float"
"ARRAY_COUNT" = "int"
"[AB]_BUTTON" = "int"
"START_BUTTON" = "int"
"[LRZ]_TRIG" = "int"
"[ULRD]_JPAD" = "int"
"[ULRD]_CBUTTONS" = "int"
"SEGMENTED_TO_VIRTUAL" = "void*"
"OS_PHYSICAL_TO_K0" = "int"
"RAD_TO_DEG" = "float"
"DEG_TO_RAD" = "float"
"NULL" = "void*"
"RAND_F.*" = "float"
"RAND_I.*" = "int"
"RAND_D.*" = "double"
"RAND_RANGE" = "float"
"SIN_DEG" = "float"
"COS_DEG" = "float"
"true" = "int"
"false" = "int"
"DMG_.*" = "int"
"AUDIOCMD_.*" = "void"
"SEQCMD_.*" = "void"
"a[A-Z].*" = "void"
"ALIGN.*" = "int"
"OS_K0_TO_PHYSICAL" = "int"
"AUDIO_PLAY_SFX" = "void"

[decompme.compilers]
"tools/ido-recomp/linux/cc" = "ido5.3"