compiler_type = "ido"

[preserve_macros]
"g[DS]P.*" = "void"
"gs[DS]P.*" = "void"
"M_.*" = "float"
"ARRAY_COUNT" = "int"
"[AB]_BUTTON" = "int"
"START_BUTTON" = "int"
"[LRZ]_TRIG" = "int"
"[ULRD]_JPAD" = "int"
"[ULRD]_CBUTTONS" = "int"

[decompme.compilers]
"tools/ido-recomp/linux/cc" = "ido5.3"